### ISSUE TITLE
My links edit screen 'freezes' when typing certain characters

### ISSUE THREAD

**Issue by Laskewitz** [pnp/sp-starter-kit#225]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

I would like to be able to add links with certain characters (for instance = or ?) in the URL. It seems like the screen freezes for a long time because of the regex check.

#### Observed Behavior

The edit link screen freezes for a while when you want to add a pretty long link with the characters = or ? in it.

#### Steps to Reproduce

1. Open footer
2. Click Edit
3. Edit or add a link
4. make sure the link is longer than 30 characters, add a = or ? at the end of it

**Comment by bcameron1231** [comment]
Cleaning up. This should be fixed in latest releases.
