### ISSUE TITLE
Alert application customizer does not render consistently when user navigates between Hub site and Associated sites

### ISSUE THREAD

**Issue by devangbhavsar89** [pnp/sp-starter-kit#229]
While I was checking the implementation of alert notification extension in an attempt to further extend it, I encountered some erroneous situation with it. As I've noticed, the alert notifications does not render consistently (each time) when user navigates between the hub site and associated sites.

_(NOTE: It does work normally when in debug mode and even with full page reloads from browser's navigation bar when deployed to target tenant, but it does not always work with partial page loads that takes places when user navigates between sites using the navigation menu.)_

As I understand, `this.context.application.navigatedEvent.add(this, this._render);` listener is already being utilized in the code sample to handle partial loading while navigating between pages. However, the rendering of alerts doesn't seem to work all the time (especially when navigating to and fro between hub site and its associated sites).

#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Alert extension to render each time when user is navigating across different pages (including hub site and its associated sites).

#### Observed Behavior

When user navigates from a hub site to one of its associated site (or vice versa), the rendering of alert notification into the header fails with following JavaScript error:

![image](https://user-images.githubusercontent.com/46373637/50822523-efeed500-1357-11e9-8162-1b1617361d80.png)

Apparently, the problem originates from `private _loadUpcomingAlerts(hubSiteUrl: string)` method, due to an exception that gets thrown because `this.context` is null while invoking following code-stub:
```
// from the Alerts list in the hub site, load the list of upcoming alerts sorted
// ascending by their end time so that alerts that expire first, are shown on top
this.context.spHttpClient
    .get(`${hubSiteUrl}/_api/web/lists/getByTitle('Alerts')/items?$filter=PnPAlertStartDateTime le datetime'${nowString}' and PnPAlertEndDateTime ge datetime'${nowString}'&$select=PnPAlertType,PnPAlertMessage,PnPAlertMoreInformation&$orderby=PnPAlertEndDateTime`, SPHttpClient.configurations.v1, {
        headers: headers
    })
```

Please note that, as I mentioned above, this problem does not occur with full reloads. It only surfaces when we try to navigate with navigation links across hub site and associated sites.

#### Steps to Reproduce

Assuming you have sp-starter-kit installed say with "contoso-" as the site-collection prefix, perform following steps in sequence:

1. Configure some notification to be displayed into the Alerts list.
2. Open https://&lt;tenant&gt;.sharepoint.com/sites/contoso-portal url in browser.
3. By now, you should be able to see the notification in the header normally.
4. Then hover over "Departments" link in the hub navigation and click on "Human Resources" or "Marketing" link, so as to navigate to ~/sites/contoso-hr or ~/sites/contoso-marketing site _(this way, we are navigating from hub site to associated site)_.
5. Most likely the alert notification functionality will break at this point, with JavaScript error show in above screen-shot. 
6. If by any chance, it doesn't break in the first attempt, try to navigate across those 3 links of  "Departments" node randomly. Doing so, it will certainly fail in following attempts.

This way when navigating between the hub site and associated sites, the alert notification extension fails to render. Further, while performing a full page reload on any of the url, it works normally back again.

#### Additional Observations

- The extension doesn't break when we navigate to links within the same hub site.
- Also I get to feel, as if this could be a SPFx extension related issue in general. 

Meanwhile I get to hear from anyone on this, maybe I'll try to do some more investigation around it and try to figure out something which could be of any help around this issue.

**Comment by awvala** [comment]
I am also seeing this behavior in our environment exactly as described above.

![image](https://user-images.githubusercontent.com/38055092/61751000-828f1880-ad6c-11e9-9473-fc8553c002ca.png)

**Comment by bcameron1231** [comment]
This should be all set. Please open a new ticket if you are still seeing any issues.
