### ISSUE TITLE
CollabFooter: "Feedback" and "Get the Mobile app" links in the way

### ISSUE THREAD

**Issue by memsim1010** [pnp/sp-starter-kit#231]
In the PoralFooter, you have the "Feedback" and "Get the Mobile App" buttons configured as links which is really quite nice.  However, in the CollabFooter, the buttons hover over "Edit my links" and are in the way.

#### Category
- [ ] Question
- [ ] Bug
- [ X] Enhancement

#### Expected or Desired Behavior
Feedback and Get the Mobile App buttons are nicely integrated into the CollabFooter similar to the PortalFooter

#### Observed Behavior

Feedback and Get the Mobile App buttons overlap CollabFooter making it challenging to add to "My Links"
#### Steps to Reproduce

Thanks for your contribution! Sharing is caring.

**Comment by Mandylf** [comment]
I agree -= is there a way to disable these

**Comment by dexteerz** [comment]
I think this will solve your problem.
Powershell with Shrepoint or Module SPO execute:
Set-SPOTenant -UserVoiceForFeedbackEnabled $false
