### ISSUE TITLE
Suggestion: Give People Directory Results Same Experience in Results List as People Web Part

### ISSUE THREAD

**Issue by Sunni-B** [pnp/sp-starter-kit#266]
#### Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

#### Expected or Desired Behavior

Our executives love the People web part. They love that when we have a project site; the Project Managers put all the team members in on the home page and they can hover over them and get details, and pull up the org chart, and so on. They expect the same behavior from the results list in the People Directory, but are disappointed that it is so different. Believe it or not, this is actually a bit of an issue for our roll-out of hub sites as we'd like to use this webpart.

**Comment by bcameron1231** [comment]
This would be a great enhancement. However, there isn't a supported mechanism for re-using the out of the box hover states as Microsoft hasn't provided an option for this yet. We are in the process of updating the people directory however to use the new Graph Toolkit.
