### ISSUE TITLE
Save-PnPTenantTemplate : Value cannot be null.

### ISSUE THREAD

**Issue by mmahmud01** [pnp/sp-starter-kit#289]
Hi,
Trying to modify Site Title and Display name in marketing landing site from sp-dev-provisioning-templates-master but its throwing error "Value cannot be null". using below powershell to save updated template:
$kit = Read-PnPTenantTemplate -Path .\starterkit.xml
Save-PnPTenantTemplate -Hierarchy $kit -Out yourstarterkit.pnp

![image](https://user-images.githubusercontent.com/33878417/59360704-96bc1080-8cfe-11e9-8586-a522cca7f653.png)

**Comment by bcameron1231** [comment]
Hi, is this still an issue for you, was it ever resolved?
