### ISSUE TITLE
Getting a Manager Name in the Employee Directory

### ISSUE THREAD

**Issue by elpinto007** [pnp/sp-starter-kit#297]
#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Is there a way to get the Manager's name to display in the People Callout? I tried including 'Manager' in the selected properties, it did not really work for me. 

#### Observed Behavior
Manager's name did not show up. I used "/_api/SP.UserProfiles.PeopleManager/GetMyProperties" and I saw the Manager key had an account, not a name.

Thank you!

**Comment by bcameron1231** [comment]
Thank you for the question. This would indeed be an enhancement as it's not currently supported functionality in the call out.. We'll take it under consideration!

**Comment by bcameron1231** [comment]
Hi, Unfortunately after looking into this enhancement, it looks like there isn't a default managed property for Manager. This would have to be created for each environment... so it's not something we can package into the provisioning.
