### ISSUE TITLE
Apply-PnPTenantTemplate -Path .\starterkit.pnp returns  Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by anandasanyal** [pnp/sp-starter-kit#321]
Apply-PnPTenantTemplate -Path .\starterkit.pnp returns  Object reference not set to an instance of an object.
At line:1 char:1           
I've changed the site URL in starterkit.xml, 

Thanks for your contribution! Sharing is caring.

**Comment by anandasanyal** [comment]
Created - New property - PnP-CollabFooter-MyLinks, as mentioned.
Uploaded - sharepoint-starter-kit.sppkg into App Catalog site.
Tried below commands
Apply-PnPTenantTemplate -Path .\starterkit.pnp -Parameters @{"PORTALURL"="/sites/SPWportal"; "MARKETINGALIAS"="SPWmarketing"; "HRALIAS"="SPWhr" }

Apply-PnPTenantTemplate -Path .\starterkit.pnp -Parameters @{"Company"="SharePoint Works";"SiteUrlPrefix"="SPW";"WeatherCity"="Sydney"}

It gives error in both.  
Thank you for your support.

**Comment by anandasanyal** [comment]
Finally I've used [https://provisioning.sharepointpnp.com/] for provisioning.
It would be good if it can be done from sp-starter-kit, powershell to have a better control.
Thank you

**Comment by eoverfield** [comment]
I believe this is similar to: https://github.com/SharePoint/sp-starter-kit/issues/274. I suggest we close this issue as it is similar to a few other general provisioning problems others have experienced.

**Comment by bcameron1231** [comment]
Closing this issue as it is duplicate, and has been inactive for a few months. If still have issues, please see if #274  is similar to your issue, if not, please open a new ticket.
