### ISSUE TITLE
Collaboration Footer: Successfully saved message always displayed

### ISSUE THREAD

**Issue by dmitryrogozhny** [pnp/sp-starter-kit#336]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

When editing personal links for the Collaboration Footer:
1. I open My Links dialog by selecting "Edit My Links".
2. In My Links dialog I select "Cancel" to close it.
3. Dialog window closes, no additional messages are displayed.

#### Observed Behavior

Every time the My Links dialog closes, "My links successfully saved!" messaged got displayed.
Even when selecting "Cancel".

When "Cancel" is selected links are not saved, but the always appearing message is confusing.

![always show save](https://user-images.githubusercontent.com/8382522/69797740-4c154e80-11e1-11ea-853b-fe7d12a58c43.gif)

#### Steps to Reproduce

1. In the Collab Footer select "Edit My Links"
2. Exit My Links dialog without saving.
3. "My links successfully saved!" message appears.

**Comment by bcameron1231** [comment]
Fixed. Closing.
