### ISSUE TITLE
Deployment to SharePoint 2019

### ISSUE THREAD

**Issue by tigertop** [pnp/sp-starter-kit#395]
## Category

- [x] Question

## Question

I tried to deploy the compatible webpart sppkg packages from the repo to SharePoint 2019. They are successfully deploy there are no errors in the AppCatalog but the webparts do not show up in "Add WebPart" menu. Do I need to rebuild the webparts from source-code? Or is there a different procedure for SharePoint 2019?

**Comment by eoverfield** [comment]
The sppgks found within the ./source/"webpart"/sharepoint/solution folder should work direct in SP 2019 when installed into your app catalog.

The only webparts that are sp 2019 ready include:
- Banner
- Followed sites
- links
- people directory
- site information
- tiles
- weather
- world clock

Our full documentation and sp 2019 ready deployment script are not yet finalized though the above webparts should work.

**Comment by tigertop** [comment]
Hi have tested with sppgks from the Github for Banner, Links and Tiles, but they don't appear neither in the "Add Apps from Organization" nor in the Webpart list when editing a page. Here is the screenshot form app catalog: 
![image](https://user-images.githubusercontent.com/12213554/82827052-401ff600-9ebf-11ea-9913-d6fe96753652.png)

Are there any extra steps needed? On this platform we have many other webaprts developed by us and some from spfx samples repo on GitHub. And all others are working.

**Comment by tigertop** [comment]
After having an another look I found the links WebPart But when I add it to a page I get this error:
![image](https://user-images.githubusercontent.com/12213554/82917419-72dff200-9f84-11ea-86c0-71301e737d8f.png)

**Comment by eoverfield** [comment]
it looks like you rebundled the sppgk? If so, just be sure to:
gulp bundle --ship
gulp package-solution --ship

**Comment by tigertop** [comment]
The screenshot is from version from sppgk from the repo (no rebundling). 
I tried to actually rebundle the webparts on my machine. And all webparts worked. Thanks for support.

**Comment by eoverfield** [comment]
@tigertop I am not sure why the links webpart was pointing back to localhost. I validated that the sppkg should have pointed to the tenant, though I committed an updated sppkg to the master branch that I validated does point back to the tenant and not to local host. Pull the latest and re-deploy if you want the project codebase.

**Comment by tigertop** [comment]
Thanks for the update.
