### ISSUE TITLE
Apply-PnPTenantTemplate : There is an error in XML document (0, 0).

### ISSUE THREAD

**Issue by sosandu** [pnp/sp-starter-kit#396]
#### Observed Behavior

When try to install using Apply-PnpTenantTemplate I get the following error
Apply-PnPTenantTemplate : There is an error in XML document (0, 0).
At line:1 char:1
+ Apply-PnPTenantTemplate -Path .\starterkit.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], InvalidOperationException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate

#### Steps to Reproduce

PS C:\> cd C:\Tools\sp-starter-kit-2\provisioning
PS C:\Tools\sp-starter-kit-2\provisioning> Apply-PnPTenantTemplate -Path .\starterkit.pnp
Apply-PnPTenantTemplate : There is an error in XML document (0, 0).
At line:1 char:1
+ Apply-PnPTenantTemplate -Path .\starterkit.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], InvalidOperationException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate
PS C:\Tools\sp-starter-kit-2\provisioning>

## Environment Details (*Development & Target environment*)
- Starter kit version: v2
- OS: Windows 10
- Target Environment:SharePoint Online
![image](https://user-images.githubusercontent.com/65890789/82791934-42f6f880-9e77-11ea-9106-b3d64bf512aa.png)

**Comment by eoverfield** [comment]
There is a good chance your workstation is using the pnp PS version of 3.13.1909.0. That should be ok, but it can cause inconsistencies. Please uninstall 3.13.1909.0 and 3.16.19.12.0 and try again. You can always reinstall these additional versions if needs be afterwards.

**Comment by sosandu** [comment]
Indeed, after removed old versions it started now.
But I have the following error:
Apply-PnPTenantTemplate : Object reference not set to an instance of an object.
At line:1 char:1
+ Apply-PnPTenantTemplate -Path .\starterkit.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate
Probably I need to put logs in Verbose
Thank you !

**Comment by eoverfield** [comment]
Good news, this looks like a duplicate now of: https://github.com/pnp/sp-starter-kit/issues/393. We are still investigating this issue, we have been unable to reproduce it.

**Comment by sosandu** [comment]
Latest lines from PS
powershell.exe Information: 0 : 2020-05-26 09:24:46.7468        [OfficeDevPnP.Core]     [0]     [Information]   File resources\resources-core.tr-tr.resx retrieved from folder  0ms
powershell.exe Information: 0 : 2020-05-26 09:24:49.1093        [Provisioning]  [14]    [Debug] Code execution scope ended      4005ms  7b5f90b5-821c-49ed-bc2d-1f5f040e236c
powershell.exe Information: 0 : 2020-05-26 09:24:49.1106        [ProvisioningTemplate WebHook Call]     [14]    [Debug]
Code execution scope started    0ms     7b5f90b5-821c-49ed-bc2d-1f5f040e236c
powershell.exe Information: 0 : 2020-05-26 09:24:49.1117        [ProvisioningTemplate WebHook Call]     [14]    [Debug]
Code execution scope ended      1ms     7b5f90b5-821c-49ed-bc2d-1f5f040e236c
powershell.exe Information: 0 : 2020-05-26 09:24:49.1136        [Provisioning]  [14]    [Debug] Code execution scope ended      217671ms        7b5f90b5-821c-49ed-bc2d-1f5f040e236c
Apply-PnPTenantTemplate : Object reference not set to an instance of an object.
At line:1 char:1
+ Apply-PnPTenantTemplate -Path .\starterkit.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate

Thank you
