### ISSUE TITLE
Banner webpart is not visible on the page

### ISSUE THREAD

**Issue by gauravgoyal5** [pnp/sp-starter-kit#398]
## Category

- [x] Bug

#### Expected or Desired Behavior

Banner webpart should be visible

#### Observed Behavior

Banner web part is not visible :
![image](https://user-images.githubusercontent.com/6926513/83236655-7c01d680-a1b1-11ea-941d-fcd7d33db4a8.png)

#### Steps to Reproduce

> Just followed the instruction to install. It installed all the sppkg file with react-banner.sppkg file
![image](https://user-images.githubusercontent.com/6926513/83236784-b53a4680-a1b1-11ea-8abd-cecc2888b004.png)

## Environment Details (*Development & Target environment*)

SharePoint online

Thanks & Regards,
Gaurav Goyal

**Comment by bcameron1231** [comment]
Hi @gauravgoyal5  Thanks for comment! Yes, actually by default the Banner Web Part is hidden because Microsoft provides one out of the box. If you would like to include the Banner, you can open the BannerWebPart.manifest.json file and set `"hiddenFromToolbox":false`
