### ISSUE TITLE
Recent Contact : Access is denied. Check credentials and try again.

### ISSUE THREAD

**Issue by tienou** [pnp/sp-starter-kit#400]
> #### Category
> * [ ]  Question
> * [x]  Bug
> * [ ]  Enhancement
> 
> I would like to use recent contacts in a modern site page. After I had the webpart, I am getting this error : Access is denied. Check credentials and try again.
> 
> #### Expected or Desired Behavior
> Display recent contacts
> 
> #### Observed Behavior
> I tried to add rights on Graph API but I keep getting this error.
> 
> ![RecentContact](https://user-images.githubusercontent.com/17547772/54987657-3b0ea080-4fb5-11e9-8694-54aa62dd0439.png)
> 
> #### Steps to Reproduce
> On a modern Site Pages, add a webpart 'Recent Contacts'
> 
> Thanks a lot.

**Comment by tienou** [comment]
for you info : language french (maybe there is a link between the bug and the language)

**Comment by bcameron1231** [comment]
When you say you added rights to the Graph API, you mean you went to API management in the Admin Center and approved the request?

**Comment by tienou** [comment]
> When you say you added rights to the Graph API, you mean you went to API management in the Admin Center and approved the request?
Yes
![image](https://user-images.githubusercontent.com/57989387/83295367-1e8c7a80-a1ef-11ea-9758-61bae3dc0f03.png)

> Also could you please update your ticket to include what version of the Starter Kit you are using.
AppCatalog indicate 1.6.0.0, is it good ?

**Comment by eoverfield** [comment]
based on the version of 1.6.0.0, this is likely version 1 of the starter kit? @tienou is this a recent install of the starter kit or a version you installed prior to 1-2 weeks ago?

**Comment by tienou** [comment]
> based on the version of 1.6.0.0, this is likely version 1 of the starter kit? @tienou is this a recent install of the starter kit or a version you installed prior to 1-2 weeks ago?

I don't understand, i downloaded the spfx here : [https://github.com/pnp/sp-starter-kit/tree/master/package](url)
How can i install the V2 ?

**Comment by tienou** [comment]
Ok, it's worked with V2.
Install path : https://github.com/pnp/sp-starter-kit/tree/master/provisioning

FYI : 
`PS C:\Users\egaillard\Downloads\sp-starter-kit-master\provisioning> Apply-PnPTenantTemplate -Path .\starterkit.pnp
AVERTISSEMENT : Une autorisation OAuth avec la ressource Microsoft Graph et la portée People.Read existe déjà.
Parameter name: permissionRequest
Apply-PnPTenantTemplate : Accès refusé. Vous n’êtes pas autorisé à effectuer cette action ou à accéder à cette
ressource.
Au caractère Ligne:1 : 1
+ Apply-PnPTenantTemplate -Path .\starterkit.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate
PS C:\Users\egaillard\Downloads\sp-starter-kit-master\provisioning> Apply-PnPTenantTemplate -Path starterkit.pnp -Parameters @{"PORTALURL"="/sites/test_Intranet"; "MARKETINGALIAS"="genesiennemarketing";   "HRALIAS"="genesiennehr" }
Apply-PnPTenantTemplate : Accès refusé. Vous n’êtes pas autorisé à effectuer cette action ou à accéder à cette
ressource.
Au caractère Ligne:1 : 1
+ Apply-PnPTenantTemplate -Path starterkit.pnp -Parameters @{"PORTALURL ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate`

**Comment by eoverfield** [comment]
@tienou were you able to successfully deploy the starter kit, v2? Which is the current master branch? If not, you may want to download the latest codebase as we made some simple adjustments to the provisioning process to assist with common provisioning errors.
