### ISSUE TITLE
Null Value Issue on Team site creations for HR and Marketing

### ISSUE THREAD

**Issue by alimughalx** [pnp/sp-starter-kit#401]
While running script line number:118 and 129 pnp:SiteCollection for team site creation, script is giving error as
Null value error on Apply-PnPTenantTemplate -Path yourstarterkit.pnp 
Parameter: Description

Solution: Update the StaterKit.Xml with adddition of description parameter ,display name of Team Sites and ran powershell script again to convert Xml back to PnP Package.
$kit = Read-PnPTenantTemplate -Path ..\source\templates\starterkit.xml
Save-PnPTenantTemplate -Template $kit -Out yourstarterkit.pnp

**Comment by ATJSM** [comment]
Thank you @alimughalx, I was getting a "value cannot be null" when provisioning the site collections. As you pointed out, filling the site descriptions and site titles in the startekit.xml file and then generating a new starterkit.pnp file solved my problem!

Thanks again!

**Comment by eoverfield** [comment]
Any chance @alimughalx  or @ATJSM would be willing to submit the update starterkit.xml and starterkit.pnp files in a PR so we can merge in?

**Comment by alimughalx** [comment]
Created a PR with starterkit.xml . Don't able to upload pnp file.

**Comment by eoverfield** [comment]
@alimughalx Thanks, I will get this merged shortly and will promote the update to others that have had similar issues.

**Comment by lincmat** [comment]
@alimughalx This fixed my deployment issue as well. Thanks for the update!

**Comment by alimughalx** [comment]
> @alimughalx This fixed my deployment issue as well. Thanks for the update!

Welcome. Glad to hear.

**Comment by alimughalx** [comment]
> @alimughalx Thanks, I will get this merged shortly and will promote the update to others that have had similar issues.

Bingo !

**Comment by eoverfield** [comment]
A recent set of commits are now included in the latest master branch. This should address the null value. Thanks go out to @alimughalx for submitting the PR.
