### ISSUE TITLE
AggregateException (PNP version installed: 3.22.2006.2)

### ISSUE THREAD

**Issue by e-diana** [pnp/sp-starter-kit#405]
PS C:\sp-starter-kit\provisioning> Apply-PnPTenantTemplate -Path .\starterkit.pnp                                       Apply-PnPTenantTemplate : Mindestens ein Fehler ist aufgetreten.                                                        In Zeile:1 Zeichen:1                                                                                                    + Apply-PnPTenantTemplate -Path .\starterkit.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], AggregateException
![AggregationException](https://user-images.githubusercontent.com/56511131/84422989-20f2c980-ac1e-11ea-8e4a-dc74be04db10.PNG)

    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate

**Comment by eoverfield** [comment]
Do you have english available within this tenant? Also, would you please enable debug logging in PS and forward that along? Lastly, please pull the latest master branch / download the latest project. We recently pushed a few bug fixes to address a few common issues that have been reported.

Also, I had problems installing the kit with PnP PS version 3.22.2006.2. I suggest removing all versions of SharePointPnPPowerShellOnline on your workstation, then installing April 2020 release as a test (3.20.2004.0) i.e. 

Install-Module -Name "SharePointPnPPowerShellOnline" -RequiredVersion 3.20.2004.0

**Comment by e-diana** [comment]
Yes english is available in the tenant now. I followed your instructions and it worked! Thank you so much! I can confirm that PnP PS version 3.20.2004.0 solved it for me. I will try to use PnP PS version 3.22.2006.2 and pull the latest project as soon as possible.
