### ISSUE TITLE
Failed to create application customizer 'ClientSideExtension.ApplicationCustomizer

### ISSUE THREAD

**Issue by nmaitreyi** [pnp/sp-starter-kit#407]
i got this error after installing a npm package $ npm install html-react-parser react react-dom . before i installed this package it was working. please help.

**Comment by bcameron1231** [comment]
Hi, thank you for the comment. This question does not seem related to the Starter Kit, if you have general development questions please head over to the SPDevDocs repository.

https://github.com/SharePoint/sp-dev-docs
