### ISSUE TITLE
Exception while invoking endpoint

### ISSUE THREAD

**Issue by ikaroamorim** [pnp/sp-starter-kit#410]
## Category

- [x] Bug

## Describe the bug

When provisioning my sharepoint starter kit v2 on my demo tenant [Sharepoint Online] I received the error  Apply-PnPTenantTemplate : Exception while invoking endpoint https://login.microsoftonline.com/ca67dfff-ffff-ffff-ffff-fffffffffdfb/oauth2/token'

I put some 'f' in the hexadecimal code, because i don`t know if it is confidential

#### Expected or Desired Behavior

Expected deploy sharepoint pnp to my environment just like a comunity demo 

#### Observed Behavior

![image](https://user-images.githubusercontent.com/44349801/85802687-d09a6200-b71b-11ea-8918-694825c7d2e8.png)

#### Steps to Reproduce
After instaled the correct version version of PnP Powerhsell Module, and in the pnp provisioning folder

1 - Connect-PnPOnline https://****.sharepoint.com/

2 - Apply-PnPTenantTemplate -Path .\starterkit.pnp -Parameters @{"PORTALURL"="/sites/demov2portal03"; "MARKETINGALIAS"="demoV2marketing03"; "HRALIAS"="demov2hr03"}

## Environment Details (*Development & Target environment*)

- **Starter kit version**: v2
- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v12
- **Browser(s)**: Chrome v83
- **Additional details**:  The user is a Global Admin of the the tenant, is the account that I create this demo tenant

**Comment by eoverfield** [comment]
We have been seeing problems installing the kit with the latest versions of PnP PS versions, i.e. 3.22.2006.2. I suggest removing all versions of SharePointPnPPowerShellOnline on your workstation, then installing April 2020 release as a test (3.20.2004.0) i.e.

Install-Module -Name "SharePointPnPPowerShellOnline" -RequiredVersion 3.20.2004.0

**Comment by ikaroamorim** [comment]
eoverfield, thank you,but I still have the problem, I'll send another pic:
![image](https://user-images.githubusercontent.com/44349801/85909978-d7e06f00-b7f2-11ea-9075-19266c417f01.png)

**Comment by expiscornovus** [comment]
@eoverfield thanks for sharing that workaround. I was running into the same invoking endpoint exception on a Developer program tenant. Reverting back to the April 2020 release of PnP PowerShell worked in my case.

**Comment by CrackerboxOnline** [comment]
Have identified that you first need to run the following in PowerShell to get a token.

Connect-PnPOnline -Url https://_tenant_-admin.sharepoint.com/ -PnPO365ManagementShell

Follow onscreen directions to obtain a token.  Note the timeout is reasonably short so have any required credentials at hand.

Then needed to reconnect on the root tenancy URL or you will get an object ref not set error

Connect-PnPOnline -Url https://_tenant_.sharepoint.com
Then
Apply-PnPTenantTemplate -Path ".\starterkit.pnp" -Parameters @{"PORTALURL"="/sites/StarterKit-Portal"; "MARKETINGALIAS"="StarterKit-Marketing"; "HRALIAS"="StarterKit-PeopleCulture" }

After that it was all good.

**Comment by eoverfield** [comment]
@CrackerboxOnline when you reconnect to connect-pnponline -url https://tenant.sharepoint.com, were you not asked to provide credentials again? Did you use -CurrentCredentials ?

**Comment by CrackerboxOnline** [comment]
Hi Eric,

Come to think of it I don't think I was (but cannot be sure) and I definitely didn't use the -CurrentCredentials flag.

Cheers,

Dave Gerrard
e: dave@crackerbox.com.au  |  m: 0417 296 560
________________________________

**Comment by ikaroamorim** [comment]
@CrackerboxOnline  thanks for helping me. I used the flag -PnPO365ManagementShell, and folowed the steps in browser.

I think the steps gone further, but at the end I faced a error again. Is there a verbose parameter to see in more details? Is possible that error is caused by a previous attempt?

Following I'll send the error and the sites deployed:

![image](https://user-images.githubusercontent.com/44349801/87158704-875b1e00-c296-11ea-91f0-127bc8cdb149.png)

![image](https://user-images.githubusercontent.com/44349801/87159050-1700cc80-c297-11ea-80db-563aef0e6277.png)

How can I check if there is something deployed?

**Comment by eoverfield** [comment]
@ikaroamorim you have gotten farther than I with the -PnPO365ManagementShell parameter. We currently do not have a tool to validate what was and wasn't installed. you can run the following command before running the apply commandlet.

Set-PnPTraceLog -On -Level Debug

that could help determine where the failure is occuring.

**Comment by CrackerboxOnline** [comment]
Hi Eric,

It might be a good idea to add a step to the general instructions to advise people to always include the Set-PnPTraceLog command before deploying a PnP solution/template to the general instructions to assist debugging.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sinhakislay** [comment]
I was able to install everything successfully following suggested steps
Install-Module -Name "SharePointPnPPowerShellOnline" -RequiredVersion 3.20.2004.0
Connect-PnPOnline -Url https://tenant-admin.sharepoint.com/ -PnPO365ManagementShell
Connect-PnPOnline -Url https://tenant.sharepoint.com
Change to the provisioning folder found in this solution's root and execute the following command (using your own tenant url and the prefix of your choosing):

Apply-PnPTenantTemplate -Path .\starterkit.pnp

**Comment by eoverfield** [comment]
@sinhakislay interesting, that is great to know the management shell is working as expected for some.

The account you used to login is set to use MFA? And when you executed the second connent-pnponline to just your tenant.sp.com url, were you asked to login again?

**Comment by sinhakislay** [comment]
@eoverfield no it is not set for MFA and for second connect PnP as well user id password was asked.

**Comment by eoverfield** [comment]
Thanks @sinhakislay, that helps confirm that without MFA, the provisioning is continuing as expected. MFA is still causing provisioning issues that appears related to PnP Provisioning, and not the kit in particular.

**Comment by IS2** [comment]
Uff, finally I get it installed with this commands:

1. Uninstall-Module -Name "SharePointPnPPowerShellOnline" -AllVersions

and then follow the steps suggested by sinhakislay

1. Install-Module -Name "SharePointPnPPowerShellOnline" -RequiredVersion 3.20.2004.0
2. Connect-PnPOnline -Url https://tenant-admin.sharepoint.com/ -PnPO365ManagementShell
3. Connect-PnPOnline -Url https://tenant.sharepoint.com
4. Change to the provisioning folder found in this solution's root and execute the following command 
6. Apply-PnPTenantTemplate -Path .\starterkit.pnp

![2020-07-23_starterkit_install](https://user-images.githubusercontent.com/8393142/88265997-ba59d480-ccce-11ea-92c2-686b1e1dd032.png)

**Comment by eoverfield** [comment]
As the root of this issue is related to MFA accounts, Im going to link this issue to https://github.com/pnp/sp-starter-kit/issues/413 and close this issue for now.
