### ISSUE TITLE
Login context does not have access to the TermGroup. If using app context, add app@sharepoint to the term group access list.

### ISSUE THREAD

**Issue by howdude230** [pnp/sp-starter-kit#412]
Debug code

powershell.exe Information: 0 : 2020-06-28 08:56:51.7431        [Term Groups]   [10]    [Debug] Code execution scope started    0ms     e13fb279-05ea-495d-b994-d6f0a745c30e                                                                    powershell.exe Warning: 0 : 2020-06-28 08:56:52.5948    [OfficeDevPnP.Core]     [0]     [Information]   Login context does not have access to the TermGroup. If using app context, add app@sharepoint to the term group access list.    0ms
powershell.exe Information: 0 : 2020-06-28 08:56:52.8630        [Term Groups]   [10]    [Debug] Code execution scope ended      1120ms  e13fb279-05ea-495d-b994-d6f0a745c30e
powershell.exe Information: 0 : 2020-06-28 08:56:52.8640        [ProvisioningTemplate WebHook Call]     [10]    [Debug]
Code execution scope started    0ms     e13fb279-05ea-495d-b994-d6f0a745c30e
powershell.exe Information: 0 : 2020-06-28 08:56:52.8640        [ProvisioningTemplate WebHook Call]     [10]    [Debug]
Code execution scope ended      0ms     e13fb279-05ea-495d-b994-d6f0a745c30e
powershell.exe Information: 0 : 2020-06-28 08:56:52.8650        [Provisioning]  [10]    [Debug] Code execution scope ended      217626ms        e13fb279-05ea-495d-b994-d6f0a745c30e
Apply-PnPTenantTemplate : Access denied. You do not have permission to perform this action or access this resource.
At line:1 char:1
+ Apply-PnPTenantTemplate -Path .\starterkit.pnp -Parameters @{"PORTALU ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate

I am the proper admin, I have followed all instructions exactly. I am the term store admin with the credentials used for the process.

**Comment by bcameron1231** [comment]
Hi Thank you. Could you please re-update your ticket using the template that was provided when creating our bug report please? All the information requested is important for us to classify and triage issues. 

Thanks!

**Comment by WorTony** [comment]
Hi,
I have had the same issue - should I raise as a new bug (and use the template as you point out)? Or wait to see if additional info is added to this one?

Tony

**Comment by eoverfield** [comment]
@WorTony please open a new issue following @bcameron1231 advice,

**Comment by bcameron1231** [comment]
Closing to consolidate with another duplicate issue. 

If you see this, please try adding app@sharepoint to the Term Store administrators group. If you need more help, please follow issue #416 

Thanks!
