### ISSUE TITLE
Apply-PnPTenantTemplate : Access Token missing or malformed

### ISSUE THREAD

**Issue by westerdaled** [pnp/sp-starter-kit#413]
## Category

- [x] Bug

## Describe the bug

Connect to my tenant using a new app registration, created via   <kbd>Initialize-PnPPowerShellAuthentication</kbd>.
The provisioning process starts with all the SPFx web parts and extensions deployed to the Tenant App Catalogue. Looking at the logs, the exception seems to be thrown when the site designs are being deployed ( see traceoutput.txt).

#### Expected or Desired Behavior

The StarterKit v2 to be deployed on my (FR) Dev tenant.

#### Observed Behavior

```

Apply-PnPTenantTemplate : Access Token missing or malformed.
At line:1 char:1
+ Apply-PnPTenantTemplate -Path starterkit.pnp -Parameters @{"PORTALURL ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTempl

```

_Note, I had previously modified the a copy of the Starterkit.xml  which was able to deploy the  web parts and extensions  to the App Catalogue but broke with the same error.  I repeated with the supplied StarterKit.pnp ._

[traceoutputsnippet.txt](https://github.com/pnp/sp-starter-kit/files/4848216/traceoutputsnippet.txt)

#### Steps to Reproduce

```
Initialize-PnPPowerShellAuthentication -ApplicationName MyPnPAuth -Tenant [myTenant].onmicrosoft.com -Store CurrentUser -Scopes `
SPO.Sites.FullControl.All, `
MSGraph.Group.ReadWrite.All,`
MSGraph.Group.Create, `
SPO.User.ReadWrite.All,`
SPO.TermStore.ReadWrite.All



Connect-PnPOnline -Url $tenantUrl -ClientId [myClientId] -Thumbprint [MyThumbprint] -Tenant [myTenant].onmicrosoft.com

Apply-PnPTenantTemplate -Path starterkit.pnp -Parameters @{"PORTALURL"="/sites/agilearchitecture"; "MARKETINGALIAS"="kanbankings";   "HRALIAS"="scrumsuperhereos" }
```

## Environment Details (*Development & Target environment*)

- **Starter kit version**: v2
- **OS**:  Windows 10 
- **Target Environment**: SharePoint Online
- **Framework**: Node  v12.18.1 SPFx 1.10
- **SharePointPnPPowerShellOnline**: 3.22.2006.2
- **Browser(s)**: Chromium Edge v79

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Hi! Thank you for reaching out to us. Do you know when the latest version of the starter kit you downloaded and tested? We've made some updates to the main branch, I'd just like to make sure you are working onthe latest.

I'm not 100% sure if this is a Starter Kit issue or a PnP PowerShell issue, I've noticed a very similar error posted in the PnP-Sites-Core repository https://github.com/pnp/PnP-Sites-Core/issues/2653

**Comment by westerdaled** [comment]
Today, I created a fresh fork of  the repo ( master), then repeated the  <kbd>Apply-PnPTenantTemplate</kbd>  above. Again the error occurs at the sample place.  I think it is when deploys the site designs  . Is there a "debug" version of the Commandlet I could install and run to give better diagnostics?   I agree this issue has been around for a while. I have seen similar errors when running a GA with MFA.

**Comment by bcameron1231** [comment]
You can use the Get-PnPException commandlet which may provide you with some more information. You would run this commandlet after the error occurs. 

We have seen other errors reported in regards to the Site Designs, but they were a different issue than you were reporting.

Can you run the get-pnpexception and let us know what it says?

**Comment by eoverfield** [comment]
@westerdaled please also turn on debugging too, that may help. before running the apply commandlet:

Set-PnPTraceLog -On -Level Debug

**Comment by westerdaled** [comment]
@eoverfield 


Opened WIndows PowerShell tab in the Windows Terrminal

Next. I recreated the app registration  as I hadn't realised the default lifespan is so short  

`
Connect-PnPOnline -Url $tenantUrl -ClientId <appid> -Thumbprint <thumbprint> -Tenant <tenant>.onmicrosoft.com

Apply-PnPTenantTemplate -Path starterkit.pnp -Parameters @{"PORTALURL"="/sites/agilearchitecture"; "MARKETINGALIAS"="kanbankings";   "HRALIAS"="scrumsuperhereos" }
Apply-PnPTenantTemplate : Access Token missing or malformed.
At line:1 char:1
+ Apply-PnPTenantTemplate -Path starterkit.pnp -Parameters @{"PORTALURL ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate

`
Next I ran <kbd>Get-PnPException</kbd>

```
get-pnpexception
get-pnpexception : Object reference not set to an instance of an object.
At line:1 char:1

```

**Comment by eoverfield** [comment]
@westerdaled I have to think your issue is actually related more to PnP PowerShell or the PnP Provisioning template, not the kit itself. When working with MFA, we are seeing seeing issues similar to the object reference you are seeing, though in my testing it was access to the app catalog. 

I understand you are not using MFA, rather your own instigated app, similar to -PnPO365ManagementShell. 

Can you confirm that the sppkg's are being installed to the app catalog before the script fails? 

An interesting experiment would be to re-bundle the .pnp package without the sppkgs or site scripts / site designs, deploying those through a different method.

**Comment by westerdaled** [comment]
@eoverfield 

Yes I went for the app registration because my GA account has MFA enforced.

All sppkg's are in the app catalogue - I did a role call and checked each one lol!

Like you I thought the app registration wouldn't be any good as a term store admin or site owner so I switched to
```

Connect-PnPOnline -Url $adminSiteUrl -PnPO365ManagementShell


```

There after I have been commenting out bits of  my <kbd>starter-kit-debug.xml</kbd> ,  <kbd>Save-PnPTenantTemplate </kbd>then Apply....the 
 

As per your suggestion I took out the site designs and the  sppkgs and this had no impact. 

Now I am trying to see what in the ROOT-TEMPLATE is causing this issue.

```
powershell.exe Information: 0 : 2020-07-07 16:01:37.8617        [ProvisioningTemplate WebHook Call]     [14]    [Debug]   Code execution scope started    0ms     c1efce94-9178-40b1-8aa7-3399638ce278
powershell.exe Information: 0 : 2020-07-07 16:01:37.8627        [ProvisioningTemplate WebHook Call]     [14]    [Debug]   Code execution scope ended      0ms     c1efce94-9178-40b1-8aa7-3399638ce278
powershell.exe Information: 0 : 2020-07-07 16:01:37.8627        [Provisioning]  [14]    [Debug] Code execution scope ended        13543ms c1efce94-9178-40b1-8aa7-3399638ce278
Apply-PnPTenantTemplate : Object reference not set to an instance of an object.
At line:1 char:1
+ Apply-PnPTenantTemplate -Path starterkit-debug.pnp -Parameters @{"POR ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplat
```

**Comment by westerdaled** [comment]
@eoverfield 

I have been doing a bit template section elimination: remove,  save and  reapply the provisioning template each time .   Now, I am still getting the same error, even with a very stripped down template ( see attached) .  Note, I had no issues deploying the site designs with the supplied starter-kit.xml.
```
Connect-PnPOnline -Url $adminSiteUrl -PnPO365ManagementShell 
$kit = Read-PnPTenantTemplate -Path ..\source\templates\starterkit-debug.xml
Save-PnPTenantTemplate -Template $kit -Out starterkit-debug.pnp -Force
Apply-PnPTenantTemplate -Path starterkit-debug.pnp -Parameters @{"PORTALURL"="/sites/agilearchitecture"; "MARKETINGALIAS"="kanbankings";   "HRALIAS"="scrumsuperhereos" } 
```

Can please give this a try . My bet it is the <kbd>Apply-PnPTenantTemplate</kbd> itself. 

[starterkit-debug.zip](https://github.com/pnp/sp-starter-kit/files/4903498/starterkit-debug.zip)

**Comment by eoverfield** [comment]
Very simple template, that is a great place to start. This issue is becoming outside the range of this project, this looks like an issue with the pnp provisioning template process.

Looking at the xml you provided, I wonder what the value of CurrentUserLoginName is. I am wondering if there is a var that is expected to have value that MFA or its like auth methods do not fill as expected.

I suggest re-posting this issue here: https://github.com/pnp/PnP-Provisioning-Schema/issues with the stripped down template you created with your auth method.

**Comment by westerdaled** [comment]
@eoverfield 

Yes , I agree that this is now not so much a starter-kit issue. I will post re-post as you suggest.  Yes would be great to insect CurentUserLoginName et al.  those values with a debugger
