### ISSUE TITLE
Issue while deploying Starter Kit V2 - fails after updating package it seems

### ISSUE THREAD

**Issue by sinhakislay** [pnp/sp-starter-kit#414]
##Category

- [x] Bug

## Describe the bug
I have followed the instruction to complete pre-requirements for installing Starter Kit v2 .
I ran the command Apply-PnPTenantTemplate -Path starterkit.pnp as per instruction and it does start processing the installation but after a while it fails with following error
Apply-PnPTenantTemplate : Exception while invoking endpoint https://login.microsoftonline.com/ff47ce9f-100c-4221-ae51-71e06b5edc04/oa
uth2/token.
At line:1 char:1
+ Apply-PnPTenantTemplate -Path starterkit.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], ApplicationException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate

#### Expected or Desired Behavior
Successful installation of Starter Kit v2

#### Observed Behavior
Installation was able to create a site called "Contoso electronics"
Also following packages were installed successfully
react-recently-used-documents-client-side-solution	

react-people-directory-client-side-solution	

react-recent-contacts-client-side-solution	

react-followed-sites-client-side-solution	

react-application-portal-footer-client-side-solution	

react-command-discuss-now-client-side-solution	

react-lob-integration-client-side-solution	

library-starter-kit-shared-client-side-solution	

react-site-information-client-side-solution	

react-recently-visited-sites-client-side-solution	

react-application-collab-footer-client-side-solution	

react-banner-client-side-solution	

js-application-redirect-client-side-solution	

react-personal-calendar-client-side-solution	

react-personal-tasks-client-side-solution	

outlook-2-sp-spfx-client-side-solution	

react-links-client-side-solution	

react-weather-client-side-solution	

react-tiles-client-side-solution	

react-personal-contacts-client-side-solution	

react-personal-email-client-side-solution	

react-application-alerts-client-side-solution	

react-world-clock-client-side-solution	

#### Steps to Reproduce

Follow the normal instructions, nothing special was done

## Environment Details (*Development & Target environment*)
- **Starter kit version**: v2
- **OS**: Windows 10 
- **Target Environment**: SharePoint Online

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Duplicate #410
