### ISSUE TITLE
Is it possible to showcase SP Starter Kit with a limited scope of tenant changes?

### ISSUE THREAD

**Issue by synergiator** [pnp/sp-starter-kit#415]
## Category

- [x] Question

## Question

Hi there, thank you for sharing this project and generally for the whole PnP initiative!

I've come across the SP Starter Kit after discovering the Lookbook and related parts on GitHub. So actually what I would like to do, is to test one or another configuration for a communication site.

While we do have a test tenant for such experiments, I've noticed that the SP Starter Kit aims to modify tenant level settings as well. Is it possible to narrow the deployment scope just to a communication site as far as possible, with this or related project?

**Comment by bcameron1231** [comment]
Hi! Thank you for the question!

Unfortunately, the Starter Kit has many tenant level configurations that need to be deployed (e.g, Site Designs, Term Store Terms, etc..). So there isn't a way to deploy using the Provisioning Service on a single site collection, as the Starter Kit deploys much more than that.

It is however entirely possible to just upload the SPPKG files to your App Catalog, and only configure the web parts and any supporting lists (e.g, Alerts) and configure it all manually. The documentation we have does outline some of those supporting assets on how you would need to configure the lists and such.

Is there some specific web parts you are looking to use or?

**Comment by eoverfield** [comment]
@synergiator another option is to take the provisioining xml template, take out the tenant settings and other sequence objects you do you need and create your own pnp provisioning package.

General steps:

You can find the base startkit.xml template file here: .\source\templates\starterkit.xml.

Create a copy of this file and make changes as necessary. You could just include a sequence step that provisions a comm site. Be aware that if you want to use any of the webparts from the kit, you will have to follow @bcameron1231 advise.

You can then read and create a new .pnp file by running the following two ps commandlets from the ./provisioning folder

$kit = Read-PnPTenantTemplate -Path ..\source\templates\starterkit-dev.xml
Save-PnPTenantTemplate -Template $kit -Out starterkit-dev.pnp

change starterkit-dev.pnp filename to whatever you create.

From there, you can now apply the custom provisioning template as you normally would, just change the name from startkit.pnp to your custom pnp package.
