### ISSUE TITLE
'Object reference not set to an instance of an object' when running Apply-PnPTenantTemplate

### ISSUE THREAD

**Issue by TylerBankston** [pnp/sp-starter-kit#417]
## Category

- [x] Question

## Question

After connecting to our SharePoint tenant using the Connect-PnPOnline https://[tenant].sharepoint.com -UseWebLogin, I cd into the provisioning directory. When I run the Apply-PnPTenantTemplate -Path starterkit.pnp, I receive the following error:

![image](https://user-images.githubusercontent.com/17317581/87741074-d88c7580-c7a0-11ea-9ecf-82134b84f462.png)

"Apply-PnPTenantTemplate : Object reference not set to an instance of an object.
At line:1 char:1
+ Apply-PnPTenantTemplate -Path starterkit.pnp"

I have reviewed all prerequisites and our tenant is properly set up according to the Get Started documentation. Please let me know if there are any additional details I can provide.

Thanks for your contribution! Sharing is caring.

**Comment by eoverfield** [comment]
@TylerBankston unfortunately for now -UseWebLogin does not work for the kit, or for PnP Provisioning templates that access the tenant app catalog at least via PowerShell. Basically no MFA accounts at the moment. We are doing what we can to find a workaround for this issue.

**Comment by CSeb96** [comment]
Hey @eoverfield, Can you let me know whats the timeline looking like for a workaround or a fix to this issue. Need to deploy SiteDesignStudio but we got MFA enabled and I am getting the same error when deploying.

Cheers

**Comment by TylerBankston** [comment]
@eoverfield - Good to know! Is this documented somewhere in the prerequisites? I want to ensure I didn't overlook anything, if not, might be good to add in the meantime.

Thank you for your prompt response and , I eagerly await a workaround!

**Comment by eoverfield** [comment]
@CSeb96 as far as we can tell, this is an issue with either PnP Provisioning Engine, PnP Provisioining templates, PnP PowerShell or PnP Core. This is outside the scope of this project through, thus we have no timeline when this may be fixed.
For SiteDesignStudio, I suggest you post issues in one of the other project issues lists. Likely PnP PowerShell: https://github.com/pnp/PnP-PowerShell

@TylerBankston this is not well documented unfortunately.

**Comment by vasqsull13** [comment]
Would a workaround be to "manually" install the starter-kit, as mentioned in the documentation - copy an paste the modules into the tenant app server - or will the MFA cause any other issues when implementing the modules? I wouldn't think there would be, but just want to be sure I'm not overlooking something.

**Comment by TylerBankston** [comment]
@vasqsull13 - good question. I can give it a shot and see what happens. I'm away from my computer this evening but will test tomorrow and report back here. Thanks for the suggestion.

**Comment by eoverfield** [comment]
The MFA issue appears to cause an issue with adding the SPFx sppkgs to the app catalog via the provisioning engine. A custom build of the starterkit.xml provisioning template, stripped of the app catalog requirement, may work well.

**Comment by vasqsull13** [comment]
I really want to “recreate” the Promoted Links of 2013 for a web part on the modern page. I want to have tiles with the pictures for links but want to control the size. Of course Quick Links is the new way in the Modern SharePoint Online experience. I can live with Quick Links in Tile view, but I want to adjust the size of them to make them smaller. I find a lot of different ways to adjust Promoted Links, but don’t work for Quick Links. You have the react-Tiles which only allow fabricons. Is there a way to use images in the tiles instead fabricons.

**Comment by socalblue-dev** [comment]
Is there a workaround for the reported issue here?  Even with MFA disabled, MS now requires additional verification on the developer tenant I created. So I am unable to run Connect-PnPOnline without using the -UseWebLogin flag.  I've looked around on how to disable the additional verification temporarily but haven't found a way to do so yet.

**Comment by eoverfield** [comment]
At this point, we can confirm that MFA, or any use of -UseWebLogin is not going to work for provisioning the starter kit because of now PnPPS and PnP Core can generate auth tokens.

You will need to create another SharePoint global admin account that does not have MFA to install the kit via PS. A backup option is to install the kit via the Lookbook site.
