### ISSUE TITLE
PnP extensions impacting load time

### ISSUE THREAD

**Issue by Mandylf** [pnp/sp-starter-kit#419]
## Category

- [x] Bug

## Describe the bug
There are 4 PnP extensions that have a severe impact on the page load time

#### Expected or Desired Behaviour

I expect some load time, but not this much
>

#### Observed Behaviour

The time to launch our intranet home page is very long and using the Page Diagnostics tool, the reason is PnP ectensions

## Environment Details (*Development & Target environment*)

- **Starter kit version**:  v1 for legacy solution
- **OS**: Windows 10
- **Target Environment**:| SharePoint Online
- **Framework**: [Node.js v6/v8/v10/v12] mmm, not sure
- **Browser(s)**:  Chromium Edge v79
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

![PnPExtensions](https://user-images.githubusercontent.com/44191278/88026018-197fe380-cb2d-11ea-9019-8b4532447564.PNG)

Is there a way to resolve this?
or to remove the extensions?

**Comment by bcameron1231** [comment]
Hi @Mandylf , Sorry to hear you are having performance issues. This is something we can look into.

You absolutely can remove the extensions. The best method is to connect to **each** site the extensions are running on using PnP PowerShell and remove the customactions that are injecting them into the page.

You would connect to your site first with `Connect-PnPOnline`

Then call `Get-PnPCustomAction -Scope Site`

This will return all the custom actions in your site. For each one you want to remove, you would grab the ID and call

`Remove-PnPCustomAction -Identity <TheIDOfYourCustomAction>`

**Comment by Mandylf** [comment]
Thank you for the update – I will give it a try

I did notice however that the name on the analytics is different from the one in PowerShell?
Is it the same thing?

[cid:image005.jpg@01D664BC.10D2AD80]

[cid:image006.jpg@01D664BC.10D2AD80]

Kind regards, ​
‑
Mandy Lightfoot
Information Manager
SolutionsPT
Address:
Unit 1 Oakfield Road, Cheadle Royal Business Park, Cheadle, SK8 3GX
Tel:
0161 495 4662<fax:0161%20495%204662>
| Fax:
0161 495 4690
Email:
mandy.lightfoot@solutionspt.com<mailto:mandy.lightfoot@solutionspt.com>
 | Web:
www.solutionspt.com<http://www.solutionspt.com/>

[Edge to Enterprise AVEVA 2020]<https://info.solutionspt.com/edge-to-enterprise-webinars>
[cid:image008.jpg@01D664BC.10D2AD80]
🌲 Consider the environment. Do you really need to print this email?
SolutionsPT Ltd accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. Any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company.

**Comment by bcameron1231** [comment]
Hi, unfortunately I can't see your images when you respond in the email. Could you post the images to the ticket? Thanks!

**Comment by Mandylf** [comment]
Hi Beau, apology, here are the screen grabs
![PnP](https://user-images.githubusercontent.com/44191278/88682454-97725a80-d0ea-11ea-8e7e-2d678a4d9a8b.jpg)
and
![PSPnP](https://user-images.githubusercontent.com/44191278/88682501-a35e1c80-d0ea-11ea-8d95-ebd76fa81eeb.jpg)

**Comment by bcameron1231** [comment]
Thank you Mandy. It's possible that some of them are not scoped to the site. Can you run Get-PnPCustomAction without the scope parameter and see if they show up? Thanks!

**Comment by eoverfield** [comment]
@Mandylf a few comments for you.

It appears as though you are connecting to your root site collection, i.e. https://"tenant".sharepoint.com, then executing get-pnpcustomaction. This will display the custom actions added to your root site collection. By default the kit does not globally deploy the kit provided SPFx extensions. Therefore you would want to connect to the specific sites deployed by the kit. Now if you added the extensions to the root site collection, that would be different.

By default the extensions added as a part of the kit are added as web scoped custom actions, not site scoped. You can see this in the starterkit.xml provisioning template if you look for <pnp:CustomActions> elements within specific provisioning template sections.

Regarding overall speed and how these extensions are affecting performance. When these extensions were built, they were built primarily as technology demonstrators, not so much as enterprise optimized solutions. Making a SPFx component truly enterprise ready often requires complexity that goes beyond the "starter" kit aspect of this project. Most of these extensions make requests to SharePoint lists on each load, they do not look to cache results for performance gains, etc.

If you are concerned about performance, and you do not need specific extensions, absolutely remove them using PnP PS, or remove them from the starterkit.xml (./source/templates) and rebuild your .pnp provisioning file. Or even better, optimize the extensions and if you are willing, commit them to your own repos on github and share your results with the community. We actively encourage the community to extend and share if possible how you all are furthering the kit.

**Comment by Mandylf** [comment]
Thank you for the feedback
