### ISSUE TITLE
Apply-PnPTenantTemplate : The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by westerdaled** [pnp/sp-starter-kit#420]
## Category

- [x] Bug

## Describe the bug

When I attempt to deploy the starter-kit.pnp;  under a non-mfa GA account on my FR Tenant, I see this error and  my dreams of a deployed vanilla starterkit, slipping away 😢!
 All apps added to app catalogue and also site designs and scripts deployed during a previous attempt (under a different GA account) .
@eoverfield , I think it is similar to my last issue:  https://github.com/pnp/sp-starter-kit/issues/413

![starter-kit 401 error](https://user-images.githubusercontent.com/937208/88188041-3997cb80-cc2f-11ea-8828-0f83e8c0e527.PNG)

```
Apply-PnPTenantTemplate : The remote server returned an error: (401) Unauthorized.
At line:1 char:1
+ Apply-PnPTenantTemplate -Path starterkit.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], WebException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate

```
see traceoutputlog.txt ( debug level)
[traceoutputlog.txt](https://github.com/pnp/sp-starter-kit/files/4960443/traceoutputlog.txt)

#### Expected or Desired Behavior

Celebrations with wild jumps of joy!

#### Observed Behavior

As above.

#### Steps to Reproduce

Created an new breaking glass GA account with an assigned Office 365 E5 license.

Added this account to the term store administrators and as an additional site collection admin on the App Catalogue site 

Updated <kbd>SharePointPnPPowerShellOnline</kbd>  module to 3.23.2007.1 and removed the previous version

```
connect-PnPOnline -Url $tenantUrl  # using breaking glass
Apply-PnPTenantTemplate -Path starterkit.pnp


```
Next , 

```
Install-Module -Name "SharePointPnPPowerShellOnline" -RequiredVersion 3.20.2004.0
Import-Module -Name "SharePointPnPPowerShellOnline" -RequiredVersion 3.20.2004.0
disconnect-PnPOnline
connect-PnPOnline -Url $tenantUrl  # using breaking glass

```
I then repeated the above steps.

Next,

```
Get-InstalledModule -Name "SharePointPnPPowerShellOnline" -RequiredVersion 3.20.2004.0 | Uninstall-Module`
Install-Module -Name "SharePointPnPPowerShellOnline" -RequiredVersion 3.23.2007.1
Get-PnPSiteDesign | Remove-PnPSiteDesign
Get-PnPSiteScript | Remove-PnPSiteScript


```

Again repeat initial install steps.

## Environment Details (*Development & Target environment*)

- **Starter kit version**: [v2]
- **OS**: [e.g. Windows 10]
- **Target Environment**:[SharePoint Online]
- **Framework**: [Node.js v10]
- **Browser(s)**: [Edge | Chromium Edge v79]
- **Additional details**:

**Comment by bcameron1231** [comment]
Hi @westerdaled, sorry to hear you are still having troubles.

Are you connecting to the Admin Site, or just connecting to a site within your environment? And to confirm, the account you are using is still an admin account with term store permissions and etc as outlined in the pre-reqs?

**Comment by westerdaled** [comment]
Hi @bcameron1231, no not the amend site. I am guessing this is something I should have tried 🙄before posting. The BG account is added to the term store admin group etc. Happy to try any other suggestions in morning.

**Comment by westerdaled** [comment]
@bcameron1231 

```
$tenant =  "<TENANT>"
$tenantUrl = "https://{0}.sharepoint.com/" -f $tenant
$adminSiteUrl = "https://{0}-admin.sharepoint.com/" -f $tenant
Connect-PnPOnline $adminSiteUrl
```

Wait, put the champagne on ice ..... and : 😢
```

powershell.exe Error: 0 : 2020-07-24 10:02:29.9317	[OfficeDevPnP.Core]	[0]	[Error]	ExecuteQuery threw following exception: System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<GetFormDigestInfoPrivateAsync>d__b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<EnsureFormDigestAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
ServerErrorTraceCorrelationId: bf23699f-9065-b000-594c-ba58b4aa9596

```

Note , I have previously deployed lookbook sites with MFA admin account, so my FR dev tenant seems ok.  I wonder if the next step is to deploy a 1) alternative site collection scoped 2) another tenant scoped provisioning template.

**Comment by bcameron1231** [comment]
Connecting to non-admin is the approach, just wanted to check and make sure. 

These are always difficult to diagnose, as we have found it's been difficult to reproduce some of the errors that people are having with the starter kit.

This BG account is also a tenant admin?

**Comment by eoverfield** [comment]
Based on the trace, it does appear as though the tenant settings <pnp:Tenant /> are all applied correctly. You are then dropping into the <pnp:Sequence /> block with includes three site collection tasks and a task to add terms. The trace you provided shows that the terms are added correctly.

Therefore, the next step of the script is to address the site collection: 

<pnp:SiteCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="pnp:CommunicationSite"
                          ProvisioningId="PORTAL"
                          Url="{parameter:PORTALURL}"
                          Owner="{CurrentUserLoginName}"
                          Title="{parameter:Company}"
                          Description="Company communication hub site"
                          IsHubSite="true"
                          SiteDesign="Topic">

The creation of the site collection, pre-applying templates, must be failing, for some reason the token provided by your authentication method does not have the permissions required to add this site collection. If you took starterkit.xml from the ./source/templates folder, stripped this down to no tenant settings, only the sequence element, and in the sequence, only have in it add the one site collection above, not even with any templates, rebuilt the proper .pnp file, and provision just based on this minimal .pnp template, my belief is this would still fail.

As @bcameron1231 mentioned, we are seeing frustrating permission failures for some people for reasons we cannot duplicate, and likely for reasons outside of the purview of this project, i.e. PnP PowerShell, or PnP Core.

The reason why these types of issues are not seen with the lookbook site is that service uses a specific authentication process based on a multi-tenant app and consent, i.e this isnt an issue with SharePoint or the kit, rather different authorization approaches and how these are handled by PnP PS / PnP Core.

**Comment by westerdaled** [comment]
@eoverfield @bcameron1231 

Thanks for the update. Funny you mention provisioning the starterkit via the lookbook as I had the exact same thought.

I guess there are some things we can try based on your analysis 

1) use a simple New-PnPSite or whatever allows me to create a communication site and convert to a hubsite. I try different authentication methods

2) try a  test multi tenant  app registration with the stripped down template and or simple PnPCommandlets. with the appropriate delegated graph  permission - tho not all at once.  I guess this is done by Azure function or runbook. 

As an aside, this isn't the only retractable issue that plaques me - getting The FAQPlusV2 Teams App migrated to V3 is proving near impossible - as it breaks the app service endpoint. I will have do a fresh install over the weekend.

**Comment by eoverfield** [comment]
Upon further review and research, this 401 unauthorized appears to be an issue with MFA, or lingering MFA accounts, as well as more recent versions of PnP PS based on updates to PnP Core. I suggest reviewing issue: https://github.com/pnp/sp-starter-kit/issues/438 for more guidance as well.

If you continue to have unauthorized errors, I would try:
- using PnP PS version 3.23.2007.1
- Try using PnP PS version 3.25.2009.1, but follow the advice from issue [438](https://github.com/pnp/sp-starter-kit/issues/438)
- Attempt to apply the tenant template using a SharePoint global admin account that has never had MFA enabled. Ensure though this account is added as a term store admin, validate that account is a SCA of the app catalog, and all other pre-reqs are fulfilled.

**Comment by westerdaled** [comment]
Hi @eoverfield 

Thanks for the update . I was just about to test out your 3 suggestions with a fresh download of the repo when I notice the readme now states that MFA is not supported.  So I will need to create a breaking glass account just to install the starterkitv2 .  The issue here, is I have previously experienced "unusual login activity " in my dev tenant for any test account that doesn't have MFA , so, will need to remember to turn MFA back on after the install.
