### ISSUE TITLE
Stock webpart does not want to display belgian stock code

### ISSUE THREAD

**Issue by SaraImmes** [pnp/sp-starter-kit#421]
I deployed the stock webpart to my tenant and added the webpart to a SharePoint site.
However it will not show me any stock information for belgian stock codes. 

For example the code for AB Inbev: ABI
The webpart shows an error 'Something went wrong. If the problem persists, contact the site administrator and give them the information in Technical Details.'

Technical details are: ERROR: No stock information found for ABI.

Can someone help me figure this out? Thanks!!

**Comment by SaraImmes** [comment]
I'm trying to add the Ontex Group stock code which should be ONTEX.

When I try another Belgian stock code for example GLPG the webpart is just displayed as blank, there is nothing there.

**Comment by bcameron1231** [comment]
Hi! The Stock Information Web Part is deprecated in this solution when we moved to V2 of the Starter Kit. Sounds like you may still be using V1? 

This web part uses the Alpha Advantage API, I would check with their service to see if they support Belgian Stock Codes. Thanks!
