### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'timeZone' of null

### ISSUE THREAD

**Issue by AlRoome** [pnp/sp-starter-kit#422]
## Category

- [x] Bug

## Describe the bug

When built and running I get the error **Uncaught (in promise) TypeError: Cannot read property 'timeZone' of null**

#### Observed Behavior

After the solution has been built and I've run gulp serve it gives me an error in the PersonalCalendar.tsx on line 35 
Uncaught (in promise) TypeError: Cannot read property 'timeZone' of null.

Any idea what the issue is referring to? 

Also getting an error before hand **Failed to load resource: the server responded with a status of 403 (Forbidden)** on the https://graph.microsoft.com/v1.0/me/mailboxSettings

```
{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token is empty.",
    "innerError": {
      "date": "2020-07-28T13:14:13",
      "request-id": "37afb36a-b69a-45f9-8b42-628b3028d0f1"
    }
  }
}
```

#### Steps to Reproduce

Download project, open the folder personalCalendar in VS Code. npm install, gulp serve.

**Comment by bcameron1231** [comment]
Hi Thank you for the comment.

A quick note, the MSGraphClient doesn't run in the local workbench, you will need to use the SharePoint hosted work bench. Subsequently, before you can make any calls to the graph endpoint, the API permissions must be configured in your tenant.

The fastest way to get to where you need to go is to just deploy the web part to your environment, and then go to the admin center and approve the permissions that are represented in the package-solution.json. From there, you should be able to gulp serve, and launch from the SharePoint hosted workbench (not local) and it should work.

Thanks!

**Comment by AlRoome** [comment]
Thanks, I'd got half way there. All working now.

**Comment by bcameron1231** [comment]
Closing as it's working.
