### ISSUE TITLE
WebParts not available in all sites in our tenant

### ISSUE THREAD

**Issue by vnetonline** [pnp/sp-starter-kit#423]
## Category

- [x] Bug

## Describe the bug

We have followed the instructions including the pre-requirements and installed the starter kit we can see the web parts on the root Site but all other sites do not have the web parts 

![image](https://user-images.githubusercontent.com/15242923/88744958-2b483300-d18c-11ea-82d8-95b496619e3a.png)

#### Expected or Desired Behavior

Webpart's should be available in all sites in the tenant

#### Observed Behavior

Webpart's not available in all sites 

## Environment Details (*Development & Target environment*)

- **Starter kit version**: V2
- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**:  Chrome v79*

**Comment by bcameron1231** [comment]
Thank you for the comment. When you say the web parts aren't available, you mean they aren't showing up in the Web Part Picker?
