### ISSUE TITLE
My Email WebPart

### ISSUE THREAD

**Issue by gristy58** [pnp/sp-starter-kit#424]
## Category

- [x] Bug

#### Expected or Desired Behavior

open outlook web new email

#### Observed Behavior

Clicking the New Email button does not go to new email in the outlook webpage and just leaves the user at a error page.

#### Steps to Reproduce

Add the webpart and have something in  your calendar.
click new email.

**Comment by eoverfield** [comment]
Apparently the path to the new email page has changed. This is being looking into, expected outcome is an updated webpart that could be deployed directly to the app catalog, as well as an updated provisioning package in case you wanted to redeploy the entire solution.

**Comment by eoverfield** [comment]
This bug has been fixed in a recently merged commit: https://github.com/pnp/sp-starter-kit/commit/81a8beb88a4bc4fba4d31ba2e2fd3de742345816

You can either obtain the latest full source from the master branch and reapply the entire kit, or simply pull the latest sppgk from ./source/react-personal-email and replace what was provisioning in the app catalog.

**Comment by gristy58** [comment]
Wow thank you that was fast. I had only installed the bundled package I assume applying the individual one next to that would cause problems ?

**Comment by eoverfield** [comment]
Oh, I missed this was related to V1. What was just provided is aimed at V2. We are not actively updating V1, thus I am not sure how quickly we could update the v1 sppkg.

If you took the sppkg from v2, just the specific email webpart, then yes, you would see a duplicate of available personal email webparts, and your existing instances of the personal email webpart would not be updated. They would need to be replaced. 

You could still have both webparts in your app catalog though.

My suggestion for the quickest fix is to look at the recent commit and you will see the one primary .tsx file that was updated. You can merge these changes over to .\solution\src\webparts\personalEmail, re build/bundle/package-solution the .\solution SPFx project, and finally update the V1 sppkg.

**Comment by gristy58** [comment]
No problem thanks for your help!
