### ISSUE TITLE
Personal Tasks New Meeting Button

### ISSUE THREAD

**Issue by gristy58** [pnp/sp-starter-kit#425]
## Category

- [x] Bug

#### Expected or Desired Behavior

"New Meeting" to go to new meeting in outlook.

#### Observed Behavior

Clicking new meeting goes to inbox.

#### Steps to Reproduce

add webpart
have meetings shown
click new meeting

**Comment by bcameron1231** [comment]
Hi, to confirm... you actually mean the Personal Calendar Web Part, and not the personal tasks Web part correct?

Unfortunately, it looks like Microsoft has stopped supporting the mechanism we use for Launching a new meeting request. We'll take a deeper look to see if any other options are available.
