### ISSUE TITLE
Resource Not Found on provisioning - https://https://graph.microsoft.com//

### ISSUE THREAD

**Issue by MrShed** [pnp/sp-starter-kit#428]
## Category

- [x] Bug

## Describe the bug

Resource Principal Not Found

#### Expected or Desired Behavior

No errors.
#### Steps to Reproduce
Apply-PnPTenantTemplate : AADSTS500011: The resource principal named https://https://graph.microsoft.com// was not found in the tenant named xxxx. This can happen if the application has not been installed by the administrator of the
tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: c89257a0-92f4-4997-bbbd-5e3eb5260c00
Correlation ID: 5ec4303c-2af7-4faf-a6f0-6b5fee9b3186
Timestamp: 2020-08-14 08:40:57Z
At line:1 char:1
+ Apply-PnPTenantTemplate -Path .\starterkit.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], MsalServiceException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate

## Environment Details (*Development & Target environment*)

- **Starter kit version**: v2
- **OS**:Windows 10
- **Target Environment**:Sharepoint Online
- **Framework**: N/A
- **Browser(s)**: N/A
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

SharePointPnPPowerShellOnline 3.24.2008.0

**Comment by eoverfield** [comment]
It appears to me as though all provisioning is failing, the default app principle used by PnP Core and SharePoint is bad.

Would you turn on logging and try again:
Set-PnPTraceLog -On -Level Debug

This can give us a more clear idea of when the error is being triggered. You may want to try on another tenant as well, it may be your tenant needs a little help.
