### ISSUE TITLE
Personal Calendar Not Showing Anything

### ISSUE THREAD

**Issue by JakeDuq** [pnp/sp-starter-kit#432]
## Category

- [x] Bug

## Describe the bug

Whenever I add the personal calendar in to a SharePoint site the web part doesn't load anything or even show any loading icons. I have removed the spkkg file and re-uploaded it and I still get nothing. I have approved the API's and removed them and added them again and still get the same issue.

#### Expected or Desired Behavior

I expect the webpart to work and pull out the user's upcoming meetings from their calendar.

#### Observed Behavior

The webpart just goes completely blank and only shows the title of the webpart.
![image](https://user-images.githubusercontent.com/44768582/91539659-90b94c00-e911-11ea-9962-c9850c7c5709.png)

#### Steps to Reproduce

I just uploaded the spkkg file into the app catalog as the tenant was already created. I have tried removing the spkkg file and adding it back again and it still worked.

## Environment Details (*Development & Target environment*)

- **Starter kit version**: [e.g. v2 for current version, v1 for legacy solution]
- **OS**: [e.g. Windows 10 | MacOS 10.15.x]
- **Target Environment**:[SharePoint Server 2019 | SharePoint Online]
- **Framework**: [Node.js v6/v8/v10/v12]
- **Browser(s)**: [e.g. Chrome v79 | Safari v22 | FireFox v31 | IE v11 | Edge | Chromium Edge v79]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

**Comment by eoverfield** [comment]
Could you check the console log? Are there any errors provided there? it sounds as though the graph calls are failing.

**Comment by JakeDuq** [comment]
> Could you check the console log? Are there any errors provided there? it sounds as though the graph calls are failing.

Thanks for your help, however I managed to fix this issue by changing the timezone on the site turns out it was incorrect. Thanks anyway.

**Comment by kbrhoades** [comment]
The problem I am seeing with the Personal Calendar is it just spinning at "_Retrieving your upcoming meetings_".  The console log is showing this - 
[covhealth.sharepoint.com-1605279094501.log](https://github.com/pnp/sp-starter-kit/files/5537485/covhealth.sharepoint.com-1605279094501.log)

I installed via the same methodology JaqDuq lists above.  It was working, albeit with the incorrect timezone, prior to my upgrading the SP Starter Kit to the newer version.  Thoughts?
