### ISSUE TITLE
Sharepoint starter kit (Sharepoint on premise 2019)

### ISSUE THREAD

**Issue by dvgoyeneche** [pnp/sp-starter-kit#433]
We are working with sharepoint 2019 on premise and we have download this package
https://github.com/SharePoint/sp-starter-kit/blob/master/package/sharepoint-starter-kit.sppkg
and imported into sharepoint. We get an error. Does this solution works on sharepoint 2019 on premise?

thanks

**Comment by bcameron1231** [comment]
Hi, Unfortunately no that .sppkg file cannot be used in SharePoint On-Premises. In V2 of the Starter Kit, all Web Parts are now separated into their own .SPPKG file. Some Web parts are not available for SharePoint 2019, but some of them are. If you want to use Web Parts, you will need to install them separately. 

Here is a link to the page that defines what Web Parts work in which environment. You will need to build and package the web parts you would like to use.
https://github.com/pnp/sp-starter-kit/tree/master/source

Thanks!
