### ISSUE TITLE
Unauthorized Access Exception

### ISSUE THREAD

**Issue by rjcg916** [pnp/sp-starter-kit#437]
## Category

- [x] Bug

## Describe the bug
When I run the command Apply-PnPTenantTemplate -Path .\starterkit.pnp using a Tenant Admin Account I get Unauthorized Access Exception
#### Expected or Desired Behavior
Expect successful Provisioning

#### Steps to Reproduce

cd Provisioning SubDir
Connect-PnPOnline -Url https://<tenant>.sharepoint.com
Set-PnPTraceLog -On -Level Debug
Apply-PnPTenantTemplate -Path .\starterkit.pnp

## Environment Details (*Development & Target environment*)

- **Starter kit version**: v2 for current version
- **OS**: Windows 10 
- **Target Environment**:SharePoint Online
- **Browser(s)**: Chrome v79 
- current version of PnPPowerShell
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

![pserror](https://user-images.githubusercontent.com/25648947/92962263-8fb20f80-f425-11ea-910f-fd219c247e2c.PNG)

**Comment by eoverfield** [comment]
This appears to be failing as soon as the first sppkg is being deployed to the tenant app catalog. Please ensure you have already provisioned a tenant app catalog, then ensure your current user is a SCA of the tenant app catalog.

**Comment by rjcg916** [comment]
sites/AppCatalog exists and user is SCA.

Sent from AT&T Yahoo Mail on Android 
 
  On Fri, Sep 11, 2020 at 12:59 PM, Eric Overfield<notifications@github.com> wrote:   


This appears to be failing as soon as the first sppkg is being deployed to the tenant app catalog. Please ensure you have already provisioned a tenant app catalog, then ensure your current user is a SCA of the tenant app catalog.

**Comment by eoverfield** [comment]
Is the account you are using set up for MFA?

**Comment by rjcg916** [comment]
MFA is disabled for this account

Sent from AT&T Yahoo Mail on Android 
 
  On Fri, Sep 11, 2020 at 1:41 PM, Eric Overfield<notifications@github.com> wrote:   


Is the account you are using set up for MFA?

**Comment by rjcg916** [comment]
Also, i was able to run the sample console app to provision a site from an existing site.  don't know if there is a csom option for tenant template that i could try.

Sent from AT&T Yahoo Mail on Android 
 
  On Fri, Sep 11, 2020 at 1:53 PM, rjcgraham@gmail.com<rjcgraham@gmail.com> wrote:   MFA is disabled for this account

Sent from AT&T Yahoo Mail on Android 
 
  On Fri, Sep 11, 2020 at 1:41 PM, Eric Overfield<notifications@github.com> wrote:   


Is the account you are using set up for MFA?

**Comment by rjcg916** [comment]
I downgraded PnP PowerShell to 3.20.2004.0 and it worked.
