### ISSUE TITLE
Getting Error when attempting to deploy to Tenant App Catalog as Tenant Admin

### ISSUE THREAD

**Issue by romanatsogeti** [pnp/sp-starter-kit#438]
## Category

- [x] Bug

I am attempting to provision the Starter Kit using Global Admin account.  I am following the instructions under [Getting Started](https://github.com/pnp/sp-starter-kit#getting-started).  I am on the second step after getting pre-requisites all validated where I am running the command to apply the starterkit.pnp bundle.

#### Expected or Desired Behavior

Expectation that  `Apply-PnPProvisioningTemplate -Path .\starterkit.pnp` will start the provisioning step.

#### Observed Behavior

```ps
Apply-PnPProvisioningTemplate -Path .\starterkit.pnp
WARNING: The source site from which the template was generated had a base template ID value of GROUP#0, while the current target site has a base template ID value
 of TENANTADMIN#0. This could cause potential issues while applying the template.
Apply-PnPProvisioningTemplate : {"odata.error":{"code":"-2146232832, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"The current user does
not have the permission to access the App Catalog."}}}
At line:1 char:1
+ Apply-PnPProvisioningTemplate -Path .\starterkit.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], Exception
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Site.ApplyProvisioningTemplate
```

#### Steps to Reproduce

```ps
Connect-PnPOnline -Url https://<tenant>-admin.sharepoint.com -Credentials (Get-Credential)
Apply-PnPProvisioningTemplate -Path .\starterkit.pnp
```

## Environment Details (*Development & Target environment*)

- **Starter kit version**: v2
- **OS**:  Windows 10
- **Target Environment**: SharePoint Online
- **Framework**:  v10

**Comment by romanatsogeti** [comment]
Thansk to #437, i saw that i can turn on TraceLog when executing the command. Here is the output:
![image](https://user-images.githubusercontent.com/67590407/92975626-8634a180-f43d-11ea-9a8e-7f3f3b6ddc06.png)

**Comment by eoverfield** [comment]
What version of pnp ps are you using? You may want to consider downgrading to 3.20.2004.0, which I have found to be successful. Though first confirm the account you are using is a listed SCA for your tenant app catalog.

**Comment by romanatsogeti** [comment]
I was using the latest version, 3.25.2009.1.  I have just downgraded to 3.20.2004.0.  Indeed, that did the trick.  I already ensured that SCA permissions were there on tenant app catalog site.
I have another dev tenant that was failing with 403 error. That one ahs MFA turned on.  I had to reset the "targeted release for everyon" option, so will want to test that tomorrow for MFA enabled tenants.

**Comment by bcameron1231** [comment]
Looks like you are using Apply-PnPProvisioningTemplate instead of Apply-PnPTenantTemplate.

`Apply-PnPTenantTemplate -Path .\starterkit.pnp`

**Comment by eoverfield** [comment]
I opened up an issue over at PnP Core as well as this appears to be an issue with how the core engine provisions.

https://github.com/pnp/PnP-Sites-Core/issues/2757

**Comment by PaoloPia** [comment]
Hi @romanatsogeti,
Thanks for using the PnP Starter Kit. Based on the provided description, you are connecting to the admin site:

Connect-PnPOnline -Url https://<tenant>-admin.sharepoint.com -Credentials (Get-Credential) <= Wrong

Instead of using the root site collection of your tenant:

Connect-PnPOnline -Url https://<tenant>.sharepoint.com -Credentials (Get-Credential) <= Correct

Moreover, you need to use Apply-PnPTenantTemplate instead of Apply-PnPProvisioningTemplate, as already highlighted by @bcameron1231 . I will close this issue. In case of any further need or issue, please create another item. Thanks.
