### ISSUE TITLE
Is there any easier way to contruct the page layout

### ISSUE THREAD

**Issue by quantrpeter** [pnp/sp-starter-kit#442]
Hi
   Is there any easier way to contruct the page layout? Stuck in the webparts i want?
thanks
Peter

**Comment by bcameron1231** [comment]
Hi, can you clarify a bit on what you are after?

**Comment by quantrpeter** [comment]
Hi @bcameron1231  , i want to know how people construct the xml that use to generate the pnp file for a site page.

**Comment by eoverfield** [comment]
@quantrpeter the easiest way is to create a site page in the browser, add webparts, sections, layouts, settings, etc, and then use Get-PnPProvisioningTemplate https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpprovisioningtemplate?view=sharepoint-ps. By default this will grab everything in a site collection, though with the xml output, you could then trim this to meet you specific needs, and you will have the XML for your particular site page as well.

**Comment by quantrpeter** [comment]
Dear Mr @eoverfield , thanks for your answer.
