### ISSUE TITLE
SP-STARTER-KIT and Office 365 CLI

### ISSUE THREAD

**Issue by rjcg916** [pnp/sp-starter-kit#443]
## Category

- [x] Question

## Question

Are the commands used in the sp-starter-kit such as Apply-PnPTenantTemplate available in Office 365 CLI?

**Comment by bcameron1231** [comment]
hi @rjcg916 Unfortunately, they aren't. The PnP Provisioning Engine is currently only available on Windows, as such, it's just not implemented in O365Cli.
