### ISSUE TITLE
Apply-PnPTenantTemplate : Your template contains artifacts that require an access token

### ISSUE THREAD

**Issue by jribi-mgen** [pnp/sp-starter-kit#444]
When I attempt to deploy the starter-kit.pnp under DEV Tenant. I have this error :
-Connect-PnPOnline -Url https://...dev.sharepoint.com -UseWebLogin
-  Get-PnPSite get sit info OK

PS D:\TFS\sp-starter-kit-master\provisioning> **Apply-PnPTenantTemplate -Path .\starterkit.pnp**
Apply-PnPTenantTemplate : **Your template contains artifacts that require an access token**. Please provide consent to the
PnP Management Shell application first by executing: Connect-PnPOnline -Graph -LaunchBrowser
Au caractère Ligne:1 : 1
+ Apply-PnPTenantTemplate -Path .\starterkit.pnp
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], PSInvalidOperationException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate
PS D:\TFS\sp-starter-kit-master\provisioning>

Environment Details  : Starter kit version: [v2]  Windows 10  Target Environment:[SharePoint Online]
SharePointPnPPowerShellOnline 3.25.2009.1

**Comment by bcameron1231** [comment]
Hi Thank you for the comment. Sounds like you may be using MFA? Please notice in the README that using MFA or accounts that require -UseWebLogin is not supported.

https://github.com/pnp/sp-starter-kit#getting-started

**Comment by jribi-mgen** [comment]
MFA is disabled on the tenant
<img width="622" alt="user" src="https://user-images.githubusercontent.com/71394979/93600805-834b2b00-f9c0-11ea-8194-539875e3afc9.png">

I can't connect without -UseWebLogin

 Connect-PnPOnline -Url https://..dev.sharepoint.com
Connect-PnPOnline : **The sign-in name or password does not match one in the Microsoft account system.**
Au caractère Ligne:1 : 
    + CategoryInfo          : NotSpecified: (:) [Connect-PnPOnline], IdcrlException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.IdcrlException,PnP.PowerShell.Commands.Base.ConnectOnline

**Comment by eoverfield** [comment]
Regarding your initial issue, you may want to review https://github.com/pnp/sp-starter-kit/issues/436#issuecomment-694936145, there were some changes recently to PnP Core that may require a few extra commandlets.

**Comment by shegaon** [comment]
I think it is related to the multifactor authentication. Although I am not sure, I manage to get it working when I connected using `Connect-PnPOnline "your-tenant-site" -Interactive`. Make sure to approve the graph api requests in the API access before doing this.
