### ISSUE TITLE
Apply-PnPTenantTemplate : The remote server returned an error: (401) Unauthorized

### ISSUE THREAD

**Issue by quantrpeter** [pnp/sp-starter-kit#445]
Hi
   I want my colleague to provision the template. She has these already:
1. Site collection admin of / site
2. term store admin
3. Office 365 roles:
  a. SharePoint admin
  b. Application developer
  c. Application admin
Any hints?
Thanks
Peter

**Comment by eoverfield** [comment]
Have you confirmed all known issues specific to the following: https://github.com/pnp/sp-starter-kit/blob/master/documentation/common-provision-results.md.

Is the account in question set for MFA? if so, that is not supported at the moment by PnP Core and the provisioning engine.

Also, could you try setting PnP PS in debug mode so we can get more granular details as to when the security validation is failing?

Set-PnPTraceLog -On -Level Debug
