### ISSUE TITLE
HubOrSiteAlertsApplicationCustomizer not working

### ISSUE THREAD

**Issue by HamEv** [pnp/sp-starter-kit#446]
## Category

- [x] Bug

#### Expected or Desired Behavior

Expected that the alerts will be shown in information panel.

#### Observed Behavior

in firefox debugger following error occures: TypeError: n is undefined

TypeError: n is undefined
    _render https://m365x801494.sharepoint.com/sites/appCatalog/ClientSideAssets/bc996340-c1e8-488d-9d62-ebd5293617fd/hub-or-site-alerts-application-customizer_afa77b2e7b60677821b316104b5bd9c5.js:29
    promise callback*p</t.prototype._render https://m365x801494.sharepoint.com/sites/appCatalog/ClientSideAssets/bc996340-c1e8-488d-9d62-ebd5293617fd/hub-or-site-alerts-application-customizer_afa77b2e7b60677821b316104b5bd9c5.js:29
    registerEvent https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    add https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    onInit https://m365x801494.sharepoint.com/sites/appCatalog/ClientSideAssets/bc996340-c1e8-488d-9d62-ebd5293617fd/hub-or-site-alerts-application-customizer_afa77b2e7b60677821b316104b5bd9c5.js:29
    _init https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    v https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    promise callback*mwqp/_</e.prototype.createExtension https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    _createApplicationCustomizer https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    _loadExtensions https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    loadExtensions https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    _loadApplicationCustomizers https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    navigate https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    promise callback*mwqp/bt</e.prototype.navigate https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    navigateToApplication https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    _navigateToApplication https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    _executePlatformCode https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    _startApplication https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    startApplication https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    _startApplication https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    _startApplication https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    start https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    promise callback*mwqp/le</e.start https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    loaderStart https://m365x801494.sharepoint.com/:55
    startSpfx https://m365x801494.sharepoint.com/:67
    <anonymous> https://m365x801494.sharepoint.com/:94
    <anonymous> https://m365x801494.sharepoint.com/:98
hub-or-site-alerts-application-customizer_afa77b2e7b60677821b316104b5bd9c5.js:29:60916
    _render https://m365x801494.sharepoint.com/sites/appCatalog/ClientSideAssets/bc996340-c1e8-488d-9d62-ebd5293617fd/hub-or-site-alerts-application-customizer_afa77b2e7b60677821b316104b5bd9c5.js:29
    (Async: promise callback)
    _render https://m365x801494.sharepoint.com/sites/appCatalog/ClientSideAssets/bc996340-c1e8-488d-9d62-ebd5293617fd/hub-or-site-alerts-application-customizer_afa77b2e7b60677821b316104b5bd9c5.js:29
    registerEvent https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    add https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    onInit https://m365x801494.sharepoint.com/sites/appCatalog/ClientSideAssets/bc996340-c1e8-488d-9d62-ebd5293617fd/hub-or-site-alerts-application-customizer_afa77b2e7b60677821b316104b5bd9c5.js:29
    _init https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    v https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    (Async: promise callback)
    createExtension https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    _createApplicationCustomizer https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    _loadExtensions https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    loadExtensions https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    _loadApplicationCustomizers https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    navigate https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    (Async: promise callback)
    navigate https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    navigateToApplication https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    _navigateToApplication https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    _executePlatformCode https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    _startApplication https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    startApplication https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    _startApplication https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    _startApplication https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    start https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    (Async: promise callback)
    start https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c79d28a9aae1e31daed842506da43bc8.js:1
    loaderStart https://m365x801494.sharepoint.com/:55
    startSpfx https://m365x801494.sharepoint.com/:67
    <anonym> https://m365x801494.sharepoint.com/:94
    <anonym> https://m365x801494.sharepoint.com/:98

#### Steps to Reproduce

1. Install react-application-alerts.sppkg manually in AppCatalog and deploy solution
2. Add a list 'Alerts' in hub root site with columns as described
3. Adding a list item
4. Register PnPCustomAction with Powershell:
   Connect-PnpOnline -Url https://[xxx].sharepoint.com
   Add-PnPCustomAction -Title HubOrSiteAlertsApplicationCustomizer -Name HubOrSiteAlertsApplicationCustomizer -Location ClientSideExtension.ApplicationCustomizer -ClientSideComponentId 29df5d8b-1d9b-4d32-971c-d66162396ed3

## Environment Details (*Development & Target environment*)

- **Starter kit version**: v2 for current version - alerts notification solution
- **OS**: Windows 10 
- **Target Environment**: SharePoint Online]
- **Browser(s)**: FireFox v80.0.1 (32-Bit)
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

**Comment by bcameron1231** [comment]
Thank you, we'll take a look!

**Comment by eoverfield** [comment]
@HamEv a few items here.

1. This error does appear to be caused because the site that has been configured to load the alerts app customizer is not a hub site or it has not been associated with a hub site. The error is being triggered when the hub site url for the site in question has not been returned by SharePoint. I suggest you ensure the site collection in question is a hub site or is associated with a hub site.

2. there is a code correction I added to the extension's primary .ts file to assist with error checking and console logging. you can apply this a few ways. pull the latest master branch and reinstall the sppkg from source/react-application-alerts/sharepoint/solution/react-application-alerts.sppkg. That should apply the fix. The project's provisioning process has also been updated.

The commit regarding this fix may be found here:
https://github.com/pnp/sp-starter-kit/commit/4fa4ddc6769686a197e6796e29f71b4f95ce48bc

**Comment by HamEv** [comment]
Many thanks to you! It's working now.
