### ISSUE TITLE
People directory - how to remove users?

### ISSUE THREAD

**Issue by dsutkiewic** [pnp/sp-starter-kit#448]
## Category

- [x] Question

## Question

Hi there! Our People Directory does not seem to be syncing with the people search. We've updated our search query to exclude people that have the msExchHideFromAddressLists (SPS-HideFromAddressLists) set to TRUE or YES, and that works in the standard people search, but People Directory seems to still pull these users. Is there some reason this may be happening? Is there something we can do to the People Directory to make it not sure users that have that attribute set? Thanks so much!!! :)

**Comment by eoverfield** [comment]
The people directory webpart included in V2 uses SharePoint's search rest api to run a people search. You will need to update the webpart as required to match your specific query, then bundle/package/redeploy.

As an example, check out: \source\react-people-directory\src\webparts\peopleDirectory\components\PeopleDirectory, currently line 103:

.get(`${this.props.webUrl}/_api/search/query?querytext='${query}'&selectproperties='FirstName,LastName,PreferredName,WorkEmail,PictureURL,WorkPhone,MobilePhone,JobTitle,Department,Skills,PastProjects'&sortlist='LastName:ascending'&sourceid='b09a7990-05ea-4af9-81ef-edfab16c4e31'&rowlimit=500`, SPHttpClient.configurations.v1, {

you can change this query to include additional specific filters to match your needs.

**Comment by dsutkiewic** [comment]
Thanks Eric!! Much appreciate your help - we will confer with our developers and move forward with updates.
