### ISSUE TITLE
Error while connecting to PnPOnline. The user has no access to the appcatalog.

### ISSUE THREAD

**Issue by noba3** [pnp/sp-starter-kit#449]
I´m getting this issue while connecting to PnPOnline:

Connect-PnPOnline : The sign-in name or password does not match one in the Microsoft account system.

I´ve MFA disabled, but even logging in to Microsoft, it wants to signing me in while sending me a SMS to my mobile number.

How can i disable this?
Thx in advance

**Comment by noba3** [comment]
I found a solution. You have to disable MFA in Office 365 Admincenter for the specific tenant admin and 
you have to disable MFA in Azure AD for the Admin too.

But now i have no access rights for the app catalog as global admin through powershell command.
So i can´t install the starterkit yet via powershell.

**Comment by bcameron1231** [comment]
You will need to make sure the current user is an admin of the App Catalog. You should be able to grant yourself those permissions.

**Comment by noba3** [comment]
Hy, thanks for the reply.
I´m global admin and tenant administrator.
Would you please tell me, where i can grant admin to the app catalog.
Im in the owners, appcatalog member and visitors group.

thx in advance.

**Comment by bcameron1231** [comment]
You should be site collection admin on the App Catalog. Also, if this is a new app catalog, there is a period of time you may have to wait before it becomes available. Do you have any update on this?

**Comment by noba3** [comment]
Found a solution. Downgraded PnP Powershell to 3.20.2004.0 and it worked then.

**Comment by eoverfield** [comment]
@noba3 I am glad you were able to install the kit. I am surprised you had to downgrade to such an older version of PnP PS. I wonder if this has to do with the application consent issue that was found in current versions of PnP PS: https://github.com/pnp/sp-starter-kit/issues/436#issuecomment-694936145.

Either way, glad you were able to find a path to success.
