### ISSUE TITLE
Redirect - how is it supposed to work?

### ISSUE THREAD

**Issue by metkhoo** [pnp/sp-starter-kit#450]
## Category

- [x] Question

## Question

I have deployed the V2 starter kit and the "Redirect" extension is present on my site collection.

I then downloaded the source for the redirect and did a "npm install" then a "gulp serve" from my local copy of the repository.  It seemed to work but needed loads of URL parameters to function,

If I call the source page without any URL parameters then nothing is redirected.

But if I manually append the following to a URL then it triggers the extension and the redirect works.

?customActions={"27f45dfa-839e-45c2-a379-fbfe627ed97c":{"location":"ClientSideExtension.ApplicationCustomizer","properties":{"redirectionsListTitle":"PnPRedirections"}}}

However, I can't believe it is "supposed" to work only when I pass all these URL parameters.

What have I done wrong?

Thanks in advance.

**Comment by metkhoo** [comment]
Just so you can see it is installed on the site collection I have attached a screenshot...

![proof](https://user-images.githubusercontent.com/18167332/95691401-d9556c00-0c16-11eb-96c2-84b97dddb63e.jpg)

**Comment by eoverfield** [comment]
With a default install, the list name in question would be: PnP Redirect Links.

The extension looks for this list in the current web in question, and if it is not found, it will create the list for you under the url ./lists/Redirections, with the default title.

This assumes the account you are using to access the web in question does have permissions to create a list if needed.

My next suggestion is that you check the network trace to see if the extension JS is actually loaded. You can then check to see if the list is accessed via the rest API.

**Comment by metkhoo** [comment]
When I do a gulp serve.  It does actually work but the URL being used has the URL parameters in it.  Is the extension supposed to work without any URL parameters?

**Comment by eoverfield** [comment]
@metkhoo I have investigated this further, I am not sure why you have needed to gulp serve this particular extension unless you were looking to make changes. Also, you should not have needed to add the querystring parameters for a given page unless the extension was not properly added to the site in question.

I have reviewed the starter kit default provisioning template. The redirection app customizer sppkg is added to the tenant app catalog and all three deployed sites are set to use the extension as well. As soon as you load any page on any of the kit deployed sites, the required redirect links list will be created for you as well.

If you want to use this extension on a different site, that should be fine, as long as you add the proper custom action via PS or another method.

The documentation for this extension has been extended to provide more guidance as well.
