### ISSUE TITLE
How to deploy and activate the Alert Application as a separate feature on a site

### ISSUE THREAD

**Issue by SopranoTony** [pnp/sp-starter-kit#451]
## Category

- [x] Question

## Question

I was able to install and test the Alert functionality on the Contoso demo site after installing the full sp starter kit on my dev tenant.  It seems like a  very useful feature to have on many sites we currently have in production.

1. I would like to know how activate this functionality on other sites apart from the Contoso Demo site.
2. I would like to know how to extract and package the alert functionality and deploy it as a standalone feature on a different tenant, without having to install the full SP Starter Kit on the tenant.

In order to activate the alert functionality on an existing site on my dev tenant where SP Starter Kit was successfully installed, I tried the following things:

Adding the following apps on an existing site:

- sharepoint-starter-kit-client-side-solution
- SPFx Fantastic 40 WebParts

Adding these apps caused the following features to be active on my site:

- pnpAlertNotification Feature
- Message Bar Feature

This did not cause the “Alerts” custom list to be created automatically, so I created it manually and added the (available) site content type “PnP Alert”, hoping this would be all it takes.

Unfortunately, when I create new alerts in the list they are not being displayed in the message bar on the home page as is the case on the Contoso Demo site. I assume I am missing a list event handler that needs to be installed on the custom Alerts list.

**Comment by bcameron1231** [comment]
After you create the lists, you would need to associate the extension via a Custom Action. We do this using Add-PnPCustomAction. Something like this... (I didn't test this command FYI) 

```
Connect-PnPOnline https://yoursite.sharepoint.com/sites/yoursite

Add-PnPCustomAction -Name "HubOrSiteAlertsApplicationCustomizer" -Title "HubOrSiteAlertsApplicationCustomizer" -ClientSideComponentId 29df5d8b-1d9b-4d32-971c-d66162396ed3 -Location "ClientSideExtension.ApplicationCustomizer" -ClientSideComponentProperties "{}" -Scope Site
```

**Comment by eoverfield** [comment]
@SopranoTony the documentation regarding the alerts extension has been updated to provide more clarity. Let us know if this helps.

https://github.com/pnp/sp-starter-kit/blob/master/source/react-application-alerts/README.md#installing-the-extension

Key points:

1. The alerts extension must be activated on a hub site or a site associated with a hub site.
2. The extension depends on a specific list, "Alerts", be hosted on the hub site.
3. The Alerts list must have specific site columns
4. The starter kit provisioning process automatically configured the proper list and sets the three provisioned sites to use this list.
5. If you want to add new sites to use the extension, you will need to use PowerShell or a similar method to add the proper custom action. This sample has been provided in the updated docs.
6. The extension may be used independent of the starter kit, though you will need to set up the proper list, add the custom actions, etc via your own PS or provisioning processes.
