### ISSUE TITLE
Customizing Starter kit in VS Code with Beautify or Prettier

### ISSUE THREAD

**Issue by jerryyasir** [pnp/sp-starter-kit#455]
## Category

- [x] Bug

#### Expected or Desired Behavior
You Open the starterkit.xml and make changes in VS Code  
Run the Read-PnpTenantTemplate command
The command should complete successfully.

#### Observed Behavior
You install Beautify or Prettier and enable on Save to modifications.  
Open the starterkit.xml and make changes to force the XML to beautify itself.  
Run the Read-PnpTenantTemplate command.  You will get invalid schema error for site collections about possible elements Templates, sites etc.

#### Steps to Reproduce
As Above

## Environment Details (*Development & Target environment*)

- **Starter kit version**: [e.g. v2 for current version, v1 for legacy solution]
- **OS**: [e.g. Windows 10 | MacOS 10.15.x]
- **Target Environment**:[| SharePoint Online]
- **Framework**: [Node.js v6/v8/v10/v12]
- **PnPPowerShell Version** : [e.g 3.26]

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Thank you for the question. While I understand you are using these for the starter kit, these extensions are unrelated to the work we do with the provisioning templates, as that's a part of the PnP Provisioning solutions.

 The XML files work as intended without the use of these third-party extensions.
