### ISSUE TITLE
cannot apply .\starterkit.pnp

### ISSUE THREAD

**Issue by melo4real** [pnp/sp-starter-kit#459]
when in the provision folder and running command:

Apply-PnPProvisioningTemplate -Path .\starterkit.pnp

I receive the following error: 

WARNING: The source site from which the template was generated had a base template ID value of GROUP#0, while the curr
ent target site has a base template ID value of SITEPAGEPUBLISHING#0. This could cause potential issues while applying
 the template.

**Comment by eoverfield** [comment]
Thank you for reporting this. This is only a warning message based on how we created the template. The actual template actions within the template have been validated to work within the communication site as well.

**Comment by bcameron1231** [comment]
Closing this as it's not an error, just a warning.
