### ISSUE TITLE
Cannot Install sp-starter-kit v2

### ISSUE THREAD

**Issue by wei-s-h** [pnp/sp-starter-kit#460]
> Please note that issues that do not follow this template will automatically be rejected.
>
> Use the following form to submit ask a question related to this repo. If you have an issue related to the SharePoint Framework or its documentation, please submit the issue at [https://github.com/SharePoint/sp-dev-docs/issues/new](https://github.com/SharePoint/sp-dev-docs/issues/new). This will help us respond to your issue faster.
> 
> ----
> 
> Thank you for asking a question. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
> 
## Category

- [x] Question

## Question

> _Provide as many details as possible to help the community answer your question._
> 

I try to install the great template (sp-starter-kit v2) on SharePoint online, unfortunately, it is fail. I would like to know what happened. I also post the error message for you to look at. If you have any way to sort it out, please give me some workaround to handle it. Thanks

> Apply-PnPTenantTemplate : Your template contains artifacts that require an access token. Please provide consent to the
> PnP Management Shell application first by executing: Register-PnPManagementShellAccess
> At line:1 char:1
> + Apply-PnPTenantTemplate -Path .\starterkit.pnp
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], PSInvalidOperationException
>     + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate

or

> PS C:\Users\Administrator\Desktop\sp-starter-kit-master\provisioning> Connect-PnPOnline -Url "https://xxx.sharepoint.com/sites/farbikam" -PnPManagementShell
> To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code DRWC56TCB to authenticate.
> PS C:\Users\Administrator\Desktop\sp-starter-kit-master\provisioning> Apply-PnPTenantTemplate -Path .\starterkit.pnp
> Apply-PnPTenantTemplate : You used a device login connection to authenticate to SharePoint. We do not support
> automatically switching context to the tenant administration site which is required to execute this cmdlet. Please use
> Connect-PnPOnline and connect to 'https://xxx-admin.sharepoint.com' with the appropriate connection parameters
> At line:1 char:1
> + Apply-PnPTenantTemplate -Path .\starterkit.pnp
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [Apply-PnPTenantTemplate], PSInvalidOperationException
>     + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate
> 
> PS C:\Users\Administrator\Desktop\sp-starter-kit-master\provisioning>

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Hi, please see the pre-requirements. 

Notice - at this time due to limitations of the PnP provisioning engine and PnP PowerShell, MFA accounts are not supported, nor are AAD applications. The Starter Kit V2 requires a tenant administrative account that would not required -UseWebLogin or -PnPO365ManagementShell when connecting to your SharePoint tenant.


As the error states, please connect using an Admin Account.

**Comment by wei-s-h** [comment]
> Hi, please see the pre-requirements.
> 
> Notice - at this time due to limitations of the PnP provisioning engine and PnP PowerShell, MFA accounts are not supported, nor are AAD applications. The Starter Kit V2 requires a tenant administrative account that would not required -UseWebLogin or -PnPO365ManagementShell when connecting to your SharePoint tenant.
> 
> As the error states, please connect using an Admin Account.

1. Yes, connect using an Admin Account
2. My Admin Account without MFA (Disable)

**Comment by eoverfield** [comment]
When you use the connect-pnponline command before applying the template, do not include -PnPMananagementShell, 

i.e. just:

Connect-PnPOnline -Url "https://xxx.sharepoint.com/sites/farbikam"

**Comment by wei-s-h** [comment]
> When you use the connect-pnponline command before applying the template, do not include -PnPMananagementShell,
> 
> i.e. just:
> 
> Connect-PnPOnline -Url "https://xxx.sharepoint.com/sites/farbikam"

@eoverfield 

it turns out that the error comes up:

> Connect-PnPOnline : The sign-in name or password does not match one in the Microsoft account system.
> At line:1 char:1
> + Connect-PnPOnline -Url "https://xxx.sharepoint.com/sites/farbikam ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Connect-PnPOnline], IdcrlException
>     + FullyQualifiedErrorId : Microsoft.SharePoint.Client.IdcrlException,PnP.PowerShell.Commands.Base.ConnectOnline

**Comment by eoverfield** [comment]
The starter kit provisioning process currently does not support scenarios If you must use -PnPManagementShell in your Connect-PnPOnline commandlet to properly authenticate, This is a current limitation with PnP Core / PnP PowerShell related to provisioning to the tenant app catalog and other aspects of the provisioning template, not necessarily an issue with the kit itself.

This is not something we can fix at this time.

The recommended path is to create a new SharePoint Global admin account in your tenant that does not have, nor never had, MFA activated. this should allow you to use Connect-PnPOnline without the -PnPManagemenShell parameter.
