### ISSUE TITLE
Continued discussion about section backgrounds for the webparts

### ISSUE THREAD

**Issue by patrikhellgren** [pnp/sp-starter-kit#463]
## Category

- [x] Question

## Question

@eoverfield earlier we had a thread going about supporting section backgrounds in my rejected PR #329 and I guess that is not monitored anymore since it has been closed, at least I never got an answer to how you want us to proceed with the section background update. I now thought I would make a PR for at least one of the webparts to get things going but then I notice that a lot of them has been reverted from SPFx 1.9.1 to 1.4.1. I guess this has to do with 2019 support. So since "supportsThemeVariants" was added in 1.8 this is now a no go.

Since some of the webparts is on at least 1.9.1 and able to support "supportsThemeVariants" we would get an inconsistent look for the different webparts and the 1.4.1 ones doesn't look good in a modern intranet using different section backgrounds.

What is your idea on how you want to move forward with this?

Sorry for posting this twice but wasn't sure that the closed PR was being monitored anymore.

**Comment by bcameron1231** [comment]
I 100% agree that we should be implementing themevariants on the 1.9 solutions. We would definitely love contributions, but just be aware we are looking to update a bunch of the web parts using MGT. So I think can implement themevariants when we move those solutions over to MGT. To see which Web Parts we plan to move to MGT, check out this issue #452

**Comment by bcameron1231** [comment]
Added background section support for Personal Calendar and Recently Visited Sites. Addressed in PR #476 476
