### ISSUE TITLE
SP Starter Kit not showing as an App to add in new Site Collections

### ISSUE THREAD

**Issue by kbrhoades** [pnp/sp-starter-kit#465]
## Category

- [x] Question

## Question

I have the SP starter Kit successfully installed and working on my tenant, there were no errors in the install or after I upgraded to version 2.  Since I updated the Starter Kit I have noticed that the last 2 site collections I created do not have the SP Starter Kit listed as an option when I go to _Add an App_.  I am also seeing that when I go into SP Admin > _Add an app to monitor_ it is the only app NOT listed.  

![image](https://user-images.githubusercontent.com/11978177/100893943-e7db3980-3489-11eb-8eea-cc2653584339.png)

Thoughts?

**Comment by bcameron1231** [comment]
The Starter Kit Web Parts are deployed as Tenant Wide Deployment, which means you don't have to add the solution to each of your sites. You should be able to use all of the web parts already on new sites when editing pages within the web part picker.

As for the monitoring piece, I'm not quite sure, I don't know if that supports tenant scoped web parts or not.... might be a question for Microsoft.
