### ISSUE TITLE
Footer with images and links

### ISSUE THREAD

**Issue by miguelisidoro** [pnp/sp-starter-kit#466]
Hello,

Does the footer component supports footer with images?
If not, any application customizer that supports imagens and links?

I found an application customizer at https://www.c-sharpcorner.com/blogs/spfx-webpart-to-configure-header-and-footer-for-modern-pages but it is not from the PnP community and the footer is always present in the page and not only when the user reaches the end of the page as expected.

Thanks,
Miguel

**Comment by bcameron1231** [comment]
The extensions in the PnP Starter Kit do not support images by default. However, these are open source and you are able to re-use and customize these extensions as much as you want. There is nothing technically preventing an extension from using images as it's just HTML, CSS and JavaScript.

**Comment by miguelisidoro** [comment]
Ok thanks @bcameron1231 . Do you know any other footer application customizer that supports html, imagens and hyperlinks?
I confess that is annonying that this doesn't come out of the box.

Thanks
Miguel

**Comment by bcameron1231** [comment]
I do not, unfortunately.  But you could probably find a developer familiar with SPFx to build one within a couple of hours. It wouldn't be too complex to achieve. :) Good luck!
