### ISSUE TITLE
I don't see the Banner webpart as an available webpart after I added the SPStarterKit package.

### ISSUE THREAD

**Issue by clohigh** [pnp/sp-starter-kit#467]
> Please note that issues that do not follow this template will automatically be rejected.
>
> Use the following form to submit an issue only if it's related to samples in this repo. If you have an issue related to the SharePoint Framework or its documentation, please submit the issue at [https://github.com/SharePoint/sp-dev-docs/issues/new](https://github.com/SharePoint/sp-dev-docs/issues/new). This will help us respond to your issue faster.
> 
> ----
> 
> Thank you for reporting an issue. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Category

- [x] Bug

#### Expected or Desired Behavior

To add the starter kit and be able to select the Banner webpart

#### Observed Behavior

I add the starter kit and I am not able to select the Banner webpart

#### Steps to Reproduce

Add the Starter Kit to the App Catalog
Add the app to your site
Try to insert the webpart, it won't be visible in the "webpart gallery").

## Environment Details (*Development & Target environment*)

Dev environment with targeted release turned on.

- **Starter kit version**: v2
- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: v.8.16.0
- **Browser(s)**: Edge

**Comment by bcameron1231** [comment]
Hi! Thanks for comment! Yes, actually by default the Banner Web Part is hidden because Microsoft provides one out of the box, we try to promote the Microsoft FIrst Party Web Parts over the custom ones (if they exist). If you would like to include the Banner, you can open the BannerWebPart.manifest.json file and set "hiddenFromToolbox":false.

So right now, this would require downloading the source, and updating the hiddenFromToolbox, and re-deploying to your environment.

**Comment by clohigh** [comment]
@bcameron1231   Thank you for that. One last thing, if you don't mind so I am crystal clear, by he 1st party ones you are speaking of using the  Image webpart, Hero, or maybe even the Highlighted Content instead of the Banner webpart?

**Comment by bcameron1231** [comment]
Yes exactly. Technically, the image web part first party, doesn't have overlays. But the highlighted content web part mimics it fairly well.

**Comment by allonestring** [comment]
I followed the instructions here https://github.com/pnp/sp-starter-kit to install the whole kit and have it working. :-)
Like clohigh, I'd like to enable the banner webpart. I can see the file BannerWebPart.manifest.json on my local drive and can change that setting. 
Can I ask a I-really-don't-know-what-I'm-doing question? How do I get the updated file onto SPO? 
Thanks!

**Comment by eoverfield** [comment]
The quick way is to open the manifest json in a code editor (vs code works). Review the following lines:

https://github.com/pnp/sp-starter-kit/blob/master/source/react-banner/src/webparts/banner/BannerWebPart.manifest.json#L17-L18

uncomment the first line, and change the second line false to true, i.e. it should be now:

```
  "supportedHosts": ["SharePointWebPart","TeamsTab"],
  "hiddenFromToolbox": false,
```

Then in the webpart solution folder, i.e. https://github.com/pnp/sp-starter-kit/blob/master/source/react-banner

npm install
gulp build
gulp bundle --ship
gulp package-solution --ship

Then upload the new sppkg for the banner webpart into your tenant app catalog.

If you want this to deploy by default when installing the entire starter kit, you will need to rebuild the pnp template found here: https://github.com/pnp/sp-starter-kit/tree/master/provisioning

**Comment by allonestring** [comment]
Thanks — I'll give it a go!
