### ISSUE TITLE
Team not being created when using Apply-PnPTenantTemplate

### ISSUE THREAD

**Issue by micromega-prog** [pnp/sp-starter-kit#468]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

After applying a pnp template I'm expecting to see a new Team created with the attributes specified in the template.

#### Observed Behavior

The Azure AD group and the associated SharePoint site collection are created when the template is applied, but the Team never appears.
#### Steps to Reproduce

# Connect to the target tenant with app-only context
Connect-PnPOnline "https://m365x302340-admin.sharepoint.com" -ClientId $clientId -Thumbprint $thumbprint -Tenant $tenant

# Apply the tenant template
Apply-PnPTenantTemplate -Path "C:\Temp\TeamTemplate.xml" -Parameters @{"TeamTitle"="PnPTeamDemoTest4";"TeamAlias"="pnpteamdemotest4"}

I'm just using the basic Team template provided in the following post: https://www.collabmagazine.com/provisioning-teams-in-microsoft-teams-using-the-pnp-provisioning-engine/

**Comment by eoverfield** [comment]
As this is not related to the starter kit, I suggest you post your question at the general pnp issues list: https://github.com/pnp/PnP/issues, or possibly at pnp PS issues: https://github.com/pnp/PnP-PowerShell/issues. I'd suggest the general issues list.
