### ISSUE TITLE
Unable to Retrieve Emails

### ISSUE THREAD

**Issue by knaveenstar** [pnp/sp-starter-kit#469]
> Please note that issues that do not follow this template will automatically be rejected.
>
> Use the following form to submit an issue only if it's related to samples in this repo. If you have an issue related to the SharePoint Framework or its documentation, please submit the issue at [https://github.com/SharePoint/sp-dev-docs/issues/new](https://github.com/SharePoint/sp-dev-docs/issues/new). This will help us respond to your issue faster.
> 
> ----
> 
> Thank you for reporting an issue. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Category

- [x] Bug

## Describe the bug
I desired to use Personal email webparts from SP Starter Kit, but I am facing following issue

Cannot read property 'request-id' of undefined

![image](https://user-images.githubusercontent.com/30283702/103610133-66257280-4f45-11eb-8796-740e84ae16d6.png)

#### Expected or Desired Behavior

> When reporting a bug, please describe the behavior you expected to occur when performing the action.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Observed Behavior

>When reporting a bug, please describe the behavior you are observing when performing the action.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Steps to Reproduce

> When reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

## Environment Details (*Development & Target environment*)

> **DELETE THIS LINE BEFORE SUBMITTING** - Complete the following (*if ignored you'll be prompted for it before we can address your issue... save the time and provide it in your initial submission*).
- **Starter kit version**: [e.g. v2 for current version, v1 for legacy solution]
- **OS**: [e.g. Windows 10 | MacOS 10.15.x]
- **Target Environment**:[SharePoint Server 2019 | SharePoint Online]
- **Framework**: [Node.js v6/v8/v10/v12]
- **PnPPowerShell Version** : [e.g 3.22.2006.2.]
- **Browser(s)**: [e.g. Chrome v79 | Safari v22 | FireFox v31 | IE v11 | Edge | Chromium Edge v79]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

## Guidelines for issue creator (DELETE AFTER READING)

> - All bug reports are welcome, please let us know what's on your mind.
> - Remember that this repository is maintained by community members who volunteer their time to help. Be courteous and patient.
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and #spfx-tooling on (SharePoint StackExchange)> [http://sharepoint.stackexchange.com/]. You can also alternatively submit your question to (SharePoint Developer group)> [https://techcommunity.microsoft.com/t5/sharepoint-developer/bd-p/SharePointDev] in the Microsoft Tech Community.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
> _(DELETE THIS SECTION AFTER READING)_

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Hi, thank you for the question. Unfortunately, you haven't filled out the entire template, which is important for us to be able to help. Can you please re-submit an issue and include a description of the bug, steps, environment details all provided by the template.
