### ISSUE TITLE
Deploying SP-Starter-Kit V2 via new PnP-Powershell fails

### ISSUE THREAD

**Issue by curacat** [pnp/sp-starter-kit#470]
## Category

- [x] Bug

## Describe the bug
Fails with error upon calling Invoke-PnPTenantTemplate

#### Expected or Desired Behavior

Deployment of SP-Starter-Kit V2

#### Observed Behavior

Runs and after a few minutes fails with the following error:

#### Steps to Reproduce
Prereqs:
https://github.com/pnp/PnP-PowerShell
https://github.com/pnp/sp-starter-kit

new Sharepoint site (Development purposes, not Live environment)
Created service account user with no 2FA and full permissions on Sharepoint
Created new App Catalog
Waited 24 hours 
Excecuted command: 
Connect-SPOService with relevant url
Invoke-PnPTenantTemplate -Path .\starterkit.pnp

Resulting output:
WARNING: You specified to remove existing content types for the list with url '/sites/contosoportal/Lists/Alerts'. We
found a list with the same url in the site. In case of a list update we cannot remove existing content types as they
can be in use by existing list items and/or documents.
Invoke-PnPTenantTemplate : The JSON object contains a trailing comma at the end which is not supported in this mode.
Change the reader options. LineNumber: 0 | BytePositionInLine: 1539.
At line:1 char:1
+ Invoke-PnPTenantTemplate -Path .\starterkit.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Invoke-PnPTenantTemplate], JsonReaderException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Tenant.InvokeTenantTemplate

## Environment Details (*Development & Target environment*)

- **Starter kit version**: v2
- **OS**: Windows 10
- **Target Environment**: SharePoint Online]
- **Framework**: 
- **PnPPowerShell Version** : PnP.PowerShell 0.3.29
- **Browser(s)**: Chrome 87.0.4280.141 (Official Build) (64-bit)
- **Additional details**: 
New sites get created in Sharepoint but they don't seem to have the functionality that V2 promises.
I have also removed the sites and re-ran the script but same result.

Any help much appreciated.

**Comment by bcameron1231** [comment]
Thank you. I have been able to reproduce the issue. I'll take a look for you.

**Comment by curacat** [comment]
Thanks bcameron1231,
Appreciate your help.

**Comment by bcameron1231** [comment]
Just a quick update, I believe I may have found the issue in the template. I am working through the testing, and I'll keep you posted after that is completed. There was a change to the JSON parser for the PnP Core module when it moved to the new version, and it's failing in the template.

**Comment by curacat** [comment]
Thank you for the update Beau, you’re a star!

**Comment by bcameron1231** [comment]
@curacat  I have fixed the issue, and I have merged the changes. Please get the latest and try the deployment again. Thank you so much for catching this!
