### ISSUE TITLE
Release preferences for your SharePoint Online tenant will need to be set as "Targeted release for everyone" option (also known as First Release)

### ISSUE THREAD

**Issue by ITCollab** [pnp/sp-starter-kit#473]
## Category

- [x] Question

## Question

In the prerequisite we have : Release preferences for your SharePoint Online tenant will need to be set as "Targeted release for everyone" option (also known as First Release)

Can someone explain why this is a pre requirment ? Is it mandatory ? This is a requirement for the deployment or it needs to be enabled also when the solution is installed and running ? 

I'm having some issue during provisoning ( no errors, the provisoning just stops ) and realized this parameters was not enabled in the admin console.

Thank you.

**Comment by bcameron1231** [comment]
Hi, thank you for the question. Actually, this isn't applicable anymore. We will be updating this readme file shortly as we have new guidance around PnP PowerShell! Thanks

**Comment by bcameron1231** [comment]
This has been updated in a PR. Thank you for pointing this out.
