### ISSUE TITLE
Targeting subsite to deploy /contosoportal demo website | Deployment triggering update of a policy at tenant level

### ISSUE THREAD

**Issue by ITCollab** [pnp/sp-starter-kit#475]
## Category

- [x] Question

## Question

Hi, i successfully delployed the starterkit in my SPO tenant. i was trying to target a subsite  for deployment with pnp-connect ( like "contoso.sharepoint.com/sites/StarterKit" ) but it seems that the websites has been deployed to "contoso.sharepoint.com/sites/"
How can i target a subsite to deploy /contosoportal demo website ? 

On top of that i noticed that the deployment has automatically triggered the udpate of a policy at the tenant level. I don't really understand why. Please find below the properties that has been impacted (external sharing) 
![image](https://user-images.githubusercontent.com/57445178/106675836-1e325380-65b6-11eb-8b97-fdfe7029f0e7.png)
Can you please explain why and for what purpose this event has been triggered  
![image](https://user-images.githubusercontent.com/57445178/106676059-82551780-65b6-11eb-9b89-87a1c0a1c172.png)

Thank you.

**Comment by bcameron1231** [comment]
Hi, thank you for your questions. 

1. You cannot target a subsite for these sites. The started kit deploys Communication Sites as site collections, with a Hub Site Architecture. _On a side note, subsites aren't recommended in SharePoint Online anymore, so you should avoid them._

2. The solution shouldn't be changing the sharing settings of your sites. As far as I can tell, the PnP Template doesn't include those settings. Are you able to provide anymore information on that activity. Does it give you more information on the user/process that changed it.

**Comment by ITCollab** [comment]
Hi, 

1 - Thank you 

2 - here is some info on what happened

![image](https://user-images.githubusercontent.com/57445178/106785984-54231680-664e-11eb-891f-0c0755f401b6.png)

The user is the account that i used to deploy the Starterkit, the IP is mine. 

![image](https://user-images.githubusercontent.com/57445178/106786896-5b96ef80-664f-11eb-86d6-89efac0e843e.png)

On this log we can see that the event was triggered by an PnP script, using the same account i used, at the same time of deployment of the kit.

Can you advice ? 

Best regards,

Marc

**Comment by bcameron1231** [comment]
Alright thank you. Let me check some of the templates, I didn't see it in there. I'll take a look and report back to you.

**Comment by eoverfield** [comment]
The provisioning template included in this project does not explicitly change sharing of any type at the tenant or site level. It is possible that pnp core or pnp powershell does something based on when sites are created without explicitly setting sharing settings, though that too would be news to me.

I would suggest you go ahead and change the settings back to enabled on your tenant, if you could, then only re-run the provisioning of this solution. Check the values again, did they change? I am not seeing how they could and it would be interesting to see what happens on a redeployment

**Comment by ITCollab** [comment]
Hello, 

1 - "It is possible that pnp core or pnp powershell does something based on when sites are created without explicitly setting sharing settings, though that too would be news to me." Note sure to understand. We don't have such automations in place. Creating a sharepoint site in our tenant should not trigger any change in the sharing policies at the tenant level.

2 - I did that on tuesday and re runned the deployment script. Not even until the end. And the same change has been triggered at the tenant level. ( Sharing policy disabled )

Best regards,

Marc

**Comment by ITCollab** [comment]
> Alright thank you. Let me check some of the templates, I didn't see it in there. I'll take a look and report back to you.

This needs to be double checked and the documentation needs to be updated if necessary.

Thanks Beau, appreciated.

**Comment by ITCollab** [comment]
> The provisioning template included in this project does not explicitly change sharing of any type at the tenant or site level. It is possible that pnp core or pnp powershell does something based on when sites are created without explicitly setting sharing settings, though that too would be news to me.
> 
> I would suggest you go ahead and change the settings back to enabled on your tenant, if you could, then only re-run the provisioning of this solution. Check the values again, did they change? I am not seeing how they could and it would be interesting to see what happens on a redeployment

**Comment by eoverfield** [comment]
@ITCollab I received from feedback from the PnP Core team. There was a bug a few months back in the provisioning engine that could cause this. @bcameron1231 and I are updating the installation instructions and documentation on how to use PnP.PowerShell moving forward. This will likely solve this issue as well.

Please stay tuned.

**Comment by bcameron1231** [comment]
Thank you @eoverfield . Curious, @ITCollab  what version of PnP PowerShell are you using?

**Comment by ITCollab** [comment]
My version is 3.23.2007.1
I don't remember where i have seen that it was recommanded to use this version.

**Comment by bcameron1231** [comment]
Ah okay. Yes this is the older version of PnP PowerShell. It is recommended to start using the new version of PnP PowerShell. Please see that information in the Getting Started section of the readme. Thanks!
