### ISSUE TITLE
Error Invoke-PnPTenantTemplate : {"odata.error":{"code":"-2147024891,  System.UnauthorizedAccessException","message":{"lang":"de-DE","value":"Zugriff verweigert. Sie haben keine  Berechtigung, diesen Vorgang auszuf\u00fchren oder auf diese Ressource zuzugreifen."}}}

### ISSUE THREAD

**Issue by NataliLogin** [pnp/sp-starter-kit#480]
When invoking Invoke-PnPTenantTemplate -Path .\starterkit.pnp I am getting the following error. My user is term store administrator. 

Does anyone experience a similar behaviour? 
**********************
nStart der Windows PowerShell-Aufzeichnung
Startzeit: 20210224073124
Benutzername: SIMPL\E519371
RunAs-Benutzer: SIMPL\E519371
Konfigurationsname: 
Computer: NBTRA081 (Microsoft Windows NT 10.0.18363.0)
Hostanwendung: C:\Windows\System32\WindowsPowerShell\v1.0\powershell_ise.exe
Prozess-ID: 13832
PSVersion: 5.1.18362.1171
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.18362.1171
BuildVersion: 10.0.18362.1171
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Die Aufzeichnung wurde gestartet. Die Ausgabedatei ist "C:\Users\E519371\OneDrive - login Berufsbildung AG\Documents\PowerShell_transcript.NBTRA081.7GEJFoYo.20210224073124.txt".
PS C:\Users\E519371\Developement\sp-starter-kit-master\provisioning> Invoke-PnPTenantTemplate -Path .\starterkit.pnp
Invoke-PnPTenantTemplate : {"odata.error":{"code":"-2147024891, 
System.UnauthorizedAccessException","message":{"lang":"de-DE","value":"Zugriff verweigert. Sie haben keine 
Berechtigung, diesen Vorgang auszuf\u00fchren oder auf diese Ressource zuzugreifen."}}}
In Zeile:1 Zeichen:1
+ Invoke-PnPTenantTemplate -Path .\starterkit.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Invoke-PnPTenantTemplate], Exception
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Tenant.InvokeTenantTemplate
Invoke-PnPTenantTemplate : {"odata.error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"de-DE","value":"Zugriff verweigert. Sie haben
keine Berechtigung, diesen Vorgang auszuf\u00fchren oder auf diese Ressource zuzugreifen."}}}
In Zeile:1 Zeichen:1
+ Invoke-PnPTenantTemplate -Path .\starterkit.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Invoke-PnPTenantTemplate], Exception
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Tenant.InvokeTenantTemplate

> 
> ----
> 
> Thank you for reporting an issue. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Category

- [x] Bug

#### Expected or Desired Behavior

> When reporting a bug, please describe the behavior you expected to occur when performing the action.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Observed Behavior

>When reporting a bug, please describe the behavior you are observing when performing the action.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Steps to Reproduce

> When reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

## Environment Details (*Development & Target environment*)

> **DELETE THIS LINE BEFORE SUBMITTING** - Complete the following (*if ignored you'll be prompted for it before we can address your issue... save the time and provide it in your initial submission*).
- **Starter kit version**: [e.g. v2 for current version, v1 for legacy solution]
- **OS**: [e.g. Windows 10 | MacOS 10.15.x]
- **Target Environment**:[SharePoint Server 2019 | SharePoint Online]
- **Framework**: [Node.js v6/v8/v10/v12]
- **PnPPowerShell Version** : [e.g 3.22.2006.2.]
- **Browser(s)**: [e.g. Chrome v79 | Safari v22 | FireFox v31 | IE v11 | Edge | Chromium Edge v79]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

## Guidelines for issue creator (DELETE AFTER READING)

> - All bug reports are welcome, please let us know what's on your mind.
> - Remember that this repository is maintained by community members who volunteer their time to help. Be courteous and patient.
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and #spfx-tooling on (SharePoint StackExchange)> [http://sharepoint.stackexchange.com/]. You can also alternatively submit your question to (SharePoint Developer group)> [https://techcommunity.microsoft.com/t5/sharepoint-developer/bd-p/SharePointDev] in the Microsoft Tech Community.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
> _(DELETE THIS SECTION AFTER READING)_

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Hi Thank you, can you confirm you are also a tenant admin?
