### ISSUE TITLE
Starter kit not adding graph permission while running with PNP.Powershell version 1.3.0 installed

### ISSUE THREAD

**Issue by pk091990** [pnp/sp-starter-kit#481]
#### Category
- [x] Question
- [x] Bug
- [ ] Enhancement

### Expected or Desired Behavior

Starter kit should add graph permission with PNP.PowerShell 1.3.0 version.

#### Observed Behavior
Starter kit not adding graph permission while running with PNP.PowerShell 1.3.0 version. Tried with below set of versions

- **SharePointPnPPowerShellOnline 3.20.2004.0** - Working fine.
- **SharePointPnPPowerShellOnline 3.25.2009.1**- 401 Unauthorized error on Apply-PnPTenantTemplate , not able to create sites
- **PNP.Powersehll 1.3.0** - Follow steps given [here](https://pnp.github.io/powershell/articles/upgrading.html) and change command from Apply-PnPTenantTemplate to Invoke-PnPTenantTemplate. Created 3 sites but not adding graph permissions.
 
#### Steps to Reproduce
Earlier I had PS v3.25 installed on my system but it was giving 401 error , So I followed steps given [here ](https://pnp.github.io/powershell/articles/upgrading.html) and install PNP.Powershell and do the below mentioned changes i.e. 
1: Uninstall "SharePointPnPPowerShellOnline" all old versions and install "PnP.PowerShell". 
- Uninstall-Module -Name "SharePointPnPPowerShellOnline" -AllVersions -Force
- Install-Module -Name "PnP.PowerShell"

2: For Authentication, run below set of lines as given and provide consent.
- #Register-PnPManagementShellAccess
- $creds = Get-Credential
- Connect-PnPOnline -Url "https://$tenant-admin.sharepoint.com/" -Credentials $creds

It worked fine and created 3 sites. However its not adding below graph permissions. Account has global administrator role.
Added 1st permission(_Windows Azure Active Directory_) based on the recommendation given [here ](https://spblog.net/post/2018/09/19/You-might-experience-errors-when-first-trying-new-SPFx-16-features)but no luck.
` <pnp:WebApiPermissions>
            <pnp:WebApiPermission Resource="Windows Azure Active Directory" Scope="User.Read"/>
            <pnp:WebApiPermission Resource="Microsoft Graph" Scope="Group.Read.All"/>
            <pnp:WebApiPermission Resource="Microsoft Graph" Scope="User.Read"/>
            <pnp:WebApiPermission Resource="Microsoft Graph" Scope="User.Read.All"/>
            <pnp:WebApiPermission Resource="Microsoft Graph" Scope="Mail.Read"/>
            <pnp:WebApiPermission Resource="Microsoft Graph" Scope="Calendars.Read"/>
            <pnp:WebApiPermission Resource="Microsoft Graph" Scope="Group.ReadWrite.All"/>
            <pnp:WebApiPermission Resource="Microsoft Graph" Scope="Directory.Read.All"/>
        </pnp:WebApiPermissions>`

No Pending request and no request in Approved also.
![image](https://user-images.githubusercontent.com/46436213/109765028-48f5e300-7c1a-11eb-8452-ac0c34b77c55.png)

and webpart which is using graph permission showing below error

![image](https://user-images.githubusercontent.com/46436213/109765549-084a9980-7c1b-11eb-8efc-1ed9d5c7122a.png)

Please let me know if I'm missing anything!

**Comment by bcameron1231** [comment]
Hi thank you for the issue. Did you receive any errors during the provisioning of the starter kit around this step?

**Comment by pk091990** [comment]
Hi,
No, didn't get any error while provisioning. Webparts which are consuming graph APIs are showing error which I've shared earlier.

**Comment by eoverfield** [comment]
The error you are receiving is in regards to the AAD application required for graph and aad client requests within SPFx. There is a SPO management shell commandlet that may help: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient#control-the-sharepoint-online-client-service-principal

It appears as though for some reason that AAD app is now corrupted in your tenant.
