### ISSUE TITLE
Detailed provisioning instructions for SharePoint 2019 Link not working

### ISSUE THREAD

**Issue by JoelHJ** [pnp/sp-starter-kit#489]
## Category

- [x] Bug

## Describe the bug

Detailed provisioning instructions for SharePoint 2019 link not working

#### Observed Behavior

Clicking link takes me to a page not found

## Environment Details (*Development & Target environment*)

> **DELETE THIS LINE BEFORE SUBMITTING** - Complete the following (*if ignored you'll be prompted for it before we can 

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Hi, we actually do not have support for 2019 fully yet. So we don't have that link working as of right now, but we are working on a template for 2019. With that in mind, there are some web parts that do work for 2019, which you can install manually. Those are defined on the main page of the repo.
