### ISSUE TITLE
Home Site Global Navigation / App Bar Disappeared

### ISSUE THREAD

**Issue by chamberstxdparish** [pnp/sp-starter-kit#490]
## Category

- [x] Question

## Question

Has anyone else with a site set as a Home Site had their Global Navigation / AppBar disappear after installing the SharePoint Starter Kit?

We have a SharePoint site set as a Home Site with Global Navigation enabled.
[https://docs.microsoft.com/en-us/sharepoint/home-site](url)
[https://docs.microsoft.com/en-us/sharepoint/sharepoint-app-bar](url)

After adding the PnP Starter Kit to our tenant the global navigation from the home site has disappeared and the option within the settings cog for global navigation is no longer there.

Has anyone else experienced this issue?

**Comment by bcameron1231** [comment]
Hi, we haven't seen this. We can take a look and see if we can reproduce this issue.

**Comment by bcameron1231** [comment]
Unable to reproduce. Please open a new ticket if this is still an issue for you.
