### ISSUE TITLE
Remove a footer from a Hub site

### ISSUE THREAD

**Issue by JBCiano** [pnp/sp-starter-kit#495]
## Category

- [x] Bug

We have been having an issue with double footers and have removed the footer using PnP PowerShell as in issue 388 (https://github.com/pnp/sp-starter-kit/issues/388).  I ran the PowerShell to remove the footer and now when a new communication site is created there is only one footer.  Get-PnPCustomAction and Remove-PnPCustomAction.

However if you associate it with the hub site the Contoso footer then appears again as well as the out the box SharePoint footer.  Any advice on how to remove the hub site footer would be appreciated.

#### Expected or Desired Behavior

We would like only one footer to appear on the pages.

#### Observed Behavior
 
Double footer on hub site

#### Steps to Reproduce

Associate a communication site with the hub site and the Contoso footer then appears again as well as the out the box SharePoint footer.

## Environment Details (*Development & Target environment*)

SharePoint Online

- **Starter kit version**: SharePoint Starter Kit in SP Online
- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: [Node.js v6/v8/v10/v12]
- **PnPPowerShell Version** : 1.5.0
- **Browser(s)**: Chrome Version 90.0.4430.212 (Official Build) (64-bit)
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

**Comment by bcameron1231** [comment]
Hi, can you clarify a bit. Do you have multiple PnP Footers? Or you have 1 Footer, and 1 out of the box footer?

**Comment by JBCiano** [comment]
Hi Beau,

When the communication site is created it just has the out the box footer but when it is associated with the hub site it adds the PnP footer as well as the out the box footer.

***@***.***D757BE.755D71E0]

Thanks.

Kind regards,

Joanne


Joanne Ciano
Microsoft Solutions and Power Platform Support Consultant
t: 0333 220 0777
e: ***@***.***
w: www.tsg.com

​TSG Support now offers Live Chat! Please visit tsg.com to chat to us regarding any issues you are experiencing or click here for further information. 

You can learn about the various ways you can request support via our new support section at www.tsg.com/contact-support

Any urgent faults can still be reported by calling 0333 220 0777

If you’ve received this email by mistake, we’re sorry for bothering you. It, and any attachments, may contain information that’s confidential, so please delete it without sharing it. If you let us know, we can try to stop it from happening again. Thank you.
​
Please make sure that you scan this email and any attachments for viruses. We may monitor any emails sent or received by us, or on our behalf. If we do, this will be in line with relevant law and our own policies. 
​
Technology Services Group is the trading name of Technology Services Group Limited. Registered Office Q11, Quorum Business Park, Newcastle, NE12 8BU. Company Reg No. 04816673 VAT no. 605300983 
Before printing this email, please consider your environmental responsibility. Ask yourself whether you need a hard copy

**Comment by bcameron1231** [comment]
Thank you. I'm having trouble reproducing this. You aren't creating the communication site via a Site Design Template are you?  I create a new Communication Site, attached it to the PnP Start kit Hubsite, and I do not have a secondary footer at the bottom.
