### ISSUE TITLE
Get-pnpflow and Get-pnpflowenvironment for GCCH

### ISSUE THREAD

**Issue by lyctysplt** [pnp/sp-starter-kit#496]
## Category

- [x] Bug

#### Expected or Desired Behavior
I'm connecting to a gcch tenant - I've created the app registration and added the permissions I see that I needed. 
When I try to run get-pnpflowenvironment i get:
Error details: error invalid_client error_description:AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: xxxxxxxxxxxxxxxxxreplacedxxxxx(PnP PowerShell). Resource value from request: https://management.azure.com. Resource app ID: 797f4846-ba00-4fd7-ba43-dac1f8f63013. List of valid resources from app registration: 00000003-0000-0ff1-ce00-000000000000, 00000003-0000-0000-c000-000000000000.

I can't find this permission guid in gcch.

#### Steps to Reproduce
Connect-PnPOnline -Url 'https://[tenantid].sharepoint.us' -Interactive -ClientId 'xxx-xxxx-xx-replaced' -Tenant '[tenantid].onmicrosoft.us' -AzureEnvironment USGovernmentHigh
get-pnpflowenvironment

## Environment Details (*Development & Target environment*)
v2
Windows 10
Sharepointonline - GCCH
framework - ps7
pnpversion - pnp.powershell 1.6

- **Starter kit version**:V2
- **OS**: Windows 10
- **Target Environment**: SharePoint Online - GCCH
- **Framework**: 
- **PnPPowerShell Version** :1.6
- **Browser(s)**: none- *

**Comment by bcameron1231** [comment]
Hi, unfortunately this repository is for the starter kit. Sounds like you are looking for Help on PnP PowerShell.

https://github.com/pnp/powershell
