### ISSUE TITLE
Personal Calendar Webpart: Error Message (manifest not found) in Edit Mode

### ISSUE THREAD

**Issue by AndreSchiemann** [pnp/sp-starter-kit#498]
## Category

- [x] Bug

#### Expected or Desired Behavior

the personal calendar webpart should work.

#### Observed Behavior

**Screenshot after installation in the app catalogue:**
![2021-07-07 webpart in app catalogue](https://user-images.githubusercontent.com/76996358/124750760-235d4b00-df26-11eb-815d-e27cb65053c5.PNG)

**Screenshot after adding the webpart in a section of page (still in edit mode)**
![2021-07-07 personal calendar webpart error message](https://user-images.githubusercontent.com/76996358/124750738-1e000080-df26-11eb-9fe1-07f20b7f4ba3.PNG)

#### Steps to Reproduce

1. install manually the personal calendar webpart package as standalone version (react-personal-calendar.sppkg) in the app catalog website of SPO
2. add the personal calendar webpart at any page in a communication website

## Environment Details (*Development & Target environment*)

> **DELETE THIS LINE BEFORE SUBMITTING** - Complete the following (*if ignored you'll be prompted for it before we can address your issue... save the time and provide it in your initial submission*).
- **Starter kit version**: [e.g. v2 for current version, v1 for legacy solution]
- **OS**: Windows 10
- **Target Environment**: SharePoint Online (Tenant in Targeted Releade Mode)
- **Framework**: [Node.js v6/v8/v10/v12]
- **PnPPowerShell Version** : [e.g 3.22.2006.2.]
- **Browser(s)**: [  Chromium Edge v91]
- **Additional details**:  SPO Communication Website

**Comment by bcameron1231** [comment]
Hi. Sounds like you may have forgotten to deploy the Library Component as well with the Calendar Web Part.


Please build/package and deploy the library component 
https://github.com/pnp/sp-starter-kit/tree/master/source/library-starter-kit-shared
