### ISSUE TITLE
deploying starterkit to a default classic site collection

### ISSUE THREAD

**Issue by collabpoint** [pnp/sp-starter-kit#499]
Hi All,
A newbie here and just wanted to confirm some few things.
I have a tenant and when i go to the default url e.g https://realhomes.sharepoint.com the page loads up with a classic homepage site.
Would i be able to deploy the starterkit.pnp to it or doesn't it have to be a comms default site?

I'm planning to use the parameters powershell cmd like below:- 

`Apply-PnPTenantTemplate -Path starterkit.pnp -Parameters @{"PORTALURL"="/"; "Company"="realhomes";"WeatherCity"="Melbourne"}

As you can see i want to deploy it to the root site using  -  "PORTALURL"="/";  as above
Will this work and i don't want any hubsites created because the sites i want to add to the hubsites have already been created and i can add it later.

Also will the starter kit also deploy the webparts to the app catalog?

Thanks so much in Advance

> Please note that issues that do not follow this template will automatically be rejected.
>
> Use the following form to submit ask a question related to this repo. If you have an issue related to the SharePoint Framework or its documentation, please submit the issue at [https://github.com/SharePoint/sp-dev-docs/issues/new](https://github.com/SharePoint/sp-dev-docs/issues/new). This will help us respond to your issue faster.
> 
> ----
> 
> Thank you for asking a question. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_
## Category

- [x] Question

## Question

> _Provide as many details as possible to help the community answer your question._
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Guidelines for issue creator (DELETE AFTER READING)

> - All questions are welcome, please let us know what's on your mind.
> - Remember that this repository is maintained by community members who volunteer their time to help. Be courteous and patient.
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and #spfx-tooling on (SharePoint StackExchange)> [http://sharepoint.stackexchange.com/]. You can also alternatively submit your question to (SharePoint Developer group)> [https://techcommunity.microsoft.com/t5/sharepoint-developer/bd-p/SharePointDev] in the Microsoft Tech Community.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
> _(DELETE THIS SECTION AFTER READING)_

Thanks for your contribution! Sharing is caring.

**Comment by eoverfield** [comment]
Hi, unfortunately the kit will not quite do what you are looking to achieve based on my understanding of your questions. This kit is designed to be a technology demonstrator with only minimal configuration infused into the deployment process. That is not to say that you could not in fact take the deployment apart and use the kit as the foundation of your own particular version.

First, regarding your root site collection, the kit is going to attempt to create a new site collection at /, which should fail. The kit is designed to create a new site collection, turn that into a hub site, then create two more sites to join to the hub. There is not a command line method to stop this from occurring, though you could certainly take the pnp template we used to create the kit, https://github.com/pnp/sp-starter-kit/blob/master/source/templates/starterkit.xml, customize that to your requirements, then use this for your deployment.

The included provisioning process will attempt to install the sppkg, the SPFx bundle that includes all of the project's webparts and extensions, into your tenant's app catalog. If you end up only wanted to install this solution, you can follow the instructions found here: https://github.com/pnp/sp-starter-kit/blob/master/documentation/manual-deploy-sppkg-solution.md.

**Comment by collabpoint** [comment]
Thanks for the response.
That what i wanted to find out if the root site would work. In that case i would just create a new site collection.
If i don't add the the options to create 2 more sites will it fail?
Or the only option is to customize the tarterkit.xml template and use it for deployment?

Thanks

**Comment by bcameron1231** [comment]
If you wanted it on your root site, you could deploy the Starter Kit and do a site swap with your Root Site. 

https://docs.microsoft.com/en-us/sharepoint/modern-root-site#replace-your-root-site

**Comment by collabpoint** [comment]
Thanks Beau for your response and the tip .
Didnt know about this.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
