### ISSUE TITLE
Error Register-PnPManagementShellAccess : A parameter cannot be found that matches parameter name 'ShowConsentUrl'.

### ISSUE THREAD

**Issue by collabpoint** [pnp/sp-starter-kit#501]
Hi All,
I'm a newbie to the start kit installation
When i tried installing the webparts only using

Apply-PnPTenantTemplate -Path starterkit-spfx-only.pnp

I get this error
```

Apply-PnPTenantTemplate : Please provide consent to the PnP Management Shell application with 'Register-PnPManagementShellAccess' and
follow the steps on screen.
```

But when i run

'Register-PnPManagementShellAccess'

I get error `
Register-PnPManagementShellAccess : A parameter cannot be found that matches parameter name 'ShowConsentUrl'.`

I'm following this article [below](
https://www.toddklindt.com/blog/Lists/Posts/Post.aspx?ID=886)

But not sure why the option to be able to get the link and send it for consent approval doesn't work for me
My pnp powershell version is SharePointPnPPowerShellOnline 3.29.2101.0

Thanks in advance
> Please note that issues that do not follow this template will automatically be rejected.
>
> Use the following form to submit ask a question related to this repo. If you have an issue related to the SharePoint Framework or its documentation, please submit the issue at [https://github.com/SharePoint/sp-dev-docs/issues/new](https://github.com/SharePoint/sp-dev-docs/issues/new). This will help us respond to your issue faster.
> 
> ----
> 
> Thank you for asking a question. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_
## Category

- [x] Question

## Question

> _Provide as many details as possible to help the community answer your question._
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Guidelines for issue creator (DELETE AFTER READING)

> - All questions are welcome, please let us know what's on your mind.
> - Remember that this repository is maintained by community members who volunteer their time to help. Be courteous and patient.
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and #spfx-tooling on (SharePoint StackExchange)> [http://sharepoint.stackexchange.com/]. You can also alternatively submit your question to (SharePoint Developer group)> [https://techcommunity.microsoft.com/t5/sharepoint-developer/bd-p/SharePointDev] in the Microsoft Tech Community.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
> _(DELETE THIS SECTION AFTER READING)_

Thanks for your contribution! Sharing is caring.

**Comment by eoverfield** [comment]
Please use PnP PowerShell 1.7.0 as this was tested and should work for you. 
https://github.com/pnp/sp-starter-kit/blob/master/documentation/common-provision-results.md#error-improper-version-of-pnp-powershell-installed
you will also want to use Invoke-PnPTenantTemplate
