### ISSUE TITLE
How to successfully run npm install in 'library-starter-kit-shared'

### ISSUE THREAD

**Issue by LeoLiOneHQ** [pnp/sp-starter-kit#504]
Hello, 
I try to follow instruction and use npm install in 'library-starter-kit-shared', but it keeping shows me error on node-sass.
![image](https://user-images.githubusercontent.com/88061131/127247903-6cb708fd-bb18-4b03-910a-ed0c3962fc58.png)
How to fix this problem?

**Comment by iorivera** [comment]
I've seen this issue appear a few times, I've had to rebuild node-sass, if that doesn't work, try downgrading node js on your machine. I seem to have better luck running the starter kit  packages with node 10

**Comment by LeoLiOneHQ** [comment]
Thanks iorivera, i use node.js 10x, problem fixed
