### ISSUE TITLE
Personal Tasks WebPart -  Long task title overflows outside Task container

### ISSUE THREAD

**Issue by iorivera** [pnp/sp-starter-kit#505]
When there is a long task title in the personal tasks webpart, the title will overflow outside the TaskContainer.  I have also logged and issue at the mgt-react repo. https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/1274

**Comment by bcameron1231** [comment]
Thank you. Yes, as this is a MGT component. We'll let the MGT crew fix this.
