### ISSUE TITLE
Portal Footer Links "react-application-portal-footer"

### ISSUE THREAD

**Issue by PaulMac66** [pnp/sp-starter-kit#517]
## Category

- [x] Bug

## Describe the bug

- When a user is adding a link via the portal footer page to "**My Links**", The save button doesn't save the link.

However, If a user navigate to a collaboration page and adds the link via the collaboration footer it does so no problem.
Then when the user navigates back to the portal page with the portal footer displayed then "**My Link**" is there and is useable.
They can they go ahead and add more links from the portal page at will, as the save button is now working correctly.

#### Observed Behavior

On the Home Page on a Communication site a user tries to add a "**My Link**" via the portal footer. It allows them to open the dialog box and select "**Add Link**", they do so and fill out the Title and URL but when selecting the "**Save**" option, it doesn't save the link.

This is the error display in the dev console:

**react-dom-15-bundle_none_bb267cbf0aa3559091a6.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'concat')**
    **at o._saveEdit** (portal-footer-application-customizer_6bd076db7f04985da845b9bb1c84c17c.js:29)
    **at Object.i** (react-dom-15-bundle_none_bb267cbf0aa3559091a6.js:2)
    **at s** (react-dom-15-bundle_none_bb267cbf0aa3559091a6.js:2)
    **at Object.executeDispatchesInOrder** (react-dom-15-bundle_none_bb267cbf0aa3559091a6.js:2)
    **at u** (react-dom-15-bundle_none_bb267cbf0aa3559091a6.js:2)
    **at p** (react-dom-15-bundle_none_bb267cbf0aa3559091a6.js:2)
    ****at Array.forEach** (anonymous)**
    **at e.exports** (react-dom-15-bundle_none_bb267cbf0aa3559091a6.js:2)
    **at Object.processEventQueue** (react-dom-15-bundle_none_bb267cbf0aa3559091a6.js:2)
    **at Object.handleTopLevel [as _handleTopLevel]** (react-dom-15-bundle_none_bb267cbf0aa3559091a6.js:2)

#####################################

**NOW**

If the same user navigates to a collaboration site and uses the "**Collab footer**" it will add the link, no problem!!!
Then upon returning to the portal home page they can then continue to add links via the portal home page and portal footer as though nothing was ever wrong. 

**Does anyone have any ideas or have experience of this???**

All API Access graph options have been granted

**Name : react-application-portal-footer-client-side-solution
Product ID : 4D7C1CEA-0EF5-4143-88F6-43411D978B2F**

## Environment Details (* Targeted Release Everyone Environment*)

- **Starter kit version**: [v2]
- **OS**: [Windows 10]
- **Target Environment**:[SharePoint Online]
- **Framework**: [Node.js v14.17.6]
- **PnPPowerShell Version** : [5.1.19041.1320]
- **Browser(s)**: [Version 96.0.4664.45]

**Comment by bcameron1231** [comment]
Thank you. I have noticed this. We'll take a look!

**Comment by PaulMac66** [comment]
Did you manage to find out what the issue is?

**Comment by bcameron1231** [comment]
Hi, unfortunately I haven't had time to check this out due to the holidays, but it does look to be a coding issue where an object is undefined (can see it in the developer consoles). Hoping this is something I can tackle right after the holidays, apologies for any inconvenience!

**Comment by PaulMac66** [comment]
Hi Beau, Did you get any further forward with this issue? TIA

**Comment by PaulMac66** [comment]
Hi @bcameron1231 , Were you able to find out what was causing this issue with the footer.

**Comment by PaulMac66** [comment]
Hi @bcameron1231  , Were you able to find out what was causing this issue with the footer.

**Comment by bcameron1231** [comment]
Hi @PaulMac66, Yes I did find the issue. It's unfortunately a multitude of issues. 

1) We have an issue with the the provisioning template. It is setting the customAction properties for the footer incorrectly, to pull from the wrong user profile property. 

2) We have a small code bug in the footer, which isn't initializing the list correctly. 

I have a fix, which I will get pushed into DEV and can work with @eoverfield to get it deployed into the main branch.


For now, you'll likely need to update your CustomAction properties for the Portal Footer. You'll have to remove and update the custom action. You can make changes to the Copyright, support values to match what you need.

` Remove-PnPCustomAction -Identity "PortalFooter"`

`Add-PnPCustomAction -Name "PortalFooter" -Title "PortalFooter" -ClientSideComponentId df889434-1b1c-4f5b-ada3-086d948e4270 -ClientSideComponentProperties "{""linksListTitle"":""PnP-PortalFooter-Links"",""copyright"":""? Copyright Contoso, 2019-2020"",""support"":""support@contoso.com"",""personalItemsStorageProperty"":""personalItemsStorageProperty""}" -Location "ClientSideExtension.ApplicationCustomizer"`


Let me know if you have questions in the meantime.

**Comment by bcameron1231** [comment]
@PaulMac66  I found the issue. It's unfortunately a couple things.

1. We do have a bug in the Footer code which is not handling empty MyLinks very well.

2. We have an issue with the provisioning template, where it's setting the custom action for the footer to select an incorrect user profile property. 

A couple things we will have to do.

1. You'll need to remove the custom action, and re-register it. 

**Connect to the portal site in PowerShell** 
`Connect-PnPOnline https://yourdomain.sharepoint.com/sites/yourportalsite`

**Remove the footer**
`Remove-PnPCustomAction -Identity "PortalFooter"`

**Re-register the footer. You can change the Copyright and support values to match your company**
`Add-PnPCustomAction -Name "PortalFooter" -Title "PortalFooter" -ClientSideComponentId df889434-1b1c-4f5b-ada3-086d948e4270 -ClientSideComponentProperties "{""linksListTitle"":""PnP-PortalFooter-Links"",""copyright"":""? Copyright Contoso, _2019-2020"",""support"":""support@contoso.com"",""personalItemsStorageProperty"":""personalItemsStorageProperty""}"_ -Location "ClientSideExtension.ApplicationCustomizer"`


2. I'll get a fix pushed to DEV and then work with @eoverfield  to fix the provisioning template and moved into the main branch.

**Comment by bcameron1231** [comment]
@PaulMac66  I did find the issue. The solution is not initializing the the links correctly.

I'll be making a code change and pushing it into DEV, and then work with @eoverfield  to merge and push into the main branch.

**Comment by bcameron1231** [comment]
Additionally... if you're in a hurry. You can pull in the sppkg to redeploy from DEV. (Remove the existing package in app catalog and replace with this one).

https://github.com/pnp/sp-starter-kit/tree/dev/source/react-application-portal-footer/sharepoint/solution

Beware, Microsoft is having some issues with the current AppCatalog deployments. So I actually had to clear out the files in the ClientSideAssets library in the app catalog first, and then add the app to the App Catalog to make it work.

**Comment by PaulMac66** [comment]
I have done as you have said, I am still getting this error message after the upload:

**Invalid SharePoint App package. Error: File contains corrupted data.**

**Comment by bcameron1231** [comment]
Hmm. I don't receive this when I upload to my app catalog. @eoverfield Are you able to deploy that new sppkg I linked on the dev branch?

**Comment by PaulMac66** [comment]
@bcameron1231 and @eoverfield .
I have now managed to get the file to load onto the App Catalog. When I got the file from the link it maybe some how got corrupted in the download through a firewall.

**Original file size for the first download 171kb
Second download from another PC and setup was 227kb**

The second is the one that loaded correctly.
I will run through some tests tomorrow on the system to see if all is working ok,

Again Thank you both for your help with this.

**_This Community is second to non._**

**Comment by eoverfield** [comment]
I can confirm the filesize should be 227kb, and the dev branch solution did install for me as well now. Glad you were able to get this to work @PaulMac66. We will work to get this all merged into the main branch shortly.

**Comment by eoverfield** [comment]
Thank you @bcameron1231 for the PR, it has been merged into the main branch. The .pnp solution file along with the specific footer sppkg have been updated as well.

**Comment by PaulMac66** [comment]
@bcameron1231 and @eoverfield ,

We have run full tests on the updated footer now with numerous users on the system, and all is working as expected.

Thank you again on this matter and fix.

**Comment by PaulMac66** [comment]
Well done Team.
