### ISSUE TITLE
Update Personal Tasks Component filter out completed tasks and allow for max tasks

### ISSUE THREAD

**Issue by iorivera** [pnp/sp-starter-kit#518]
## Category

- [x] Feature request

## Is your feature request related to a problem?
>There is no way to limit the amount of tasks returned. If there are a lot of tasks in the planner or todo they will all be rendered and makes the page  longer than it should be.

## Describe the solution you'd like
> I would like to ability to customize the web part code in order to limit the amount of tasks rendered, and also be able to filter out tasks that have been marked as completed.

## Describe alternatives you've considered
> I have attempted to use the filter function mentioned in the official mgt-tasks documentation but efforts have been unsuccessful

**Comment by bcameron1231** [comment]
Unfortunately this is not something is attainable with this web part, as we are using the MGT Component for Tasks, which does not provide methods for selecting max records to return.
