### ISSUE TITLE
Read-PnpTenantTemplate There is an error in XML Document

### ISSUE THREAD

**Issue by alvmad** [pnp/sp-starter-kit#519]
I have been trying to run this v2 starter kit but is impossible mission.
I have SharePointPnPPowerShellOnline 3.29.2101.0 and when I try to launch the command $kit = Read-PnPTenantTemplate -Path ..\source\templates\starterkit.xml I get the following error

Read-PnPTenantTemplate : Error en el documento XML (0, 0).
En línea: 1 Carácter: 8
+ $kit = Read-PnPTenantTemplate -Path ..\source\templates\starterkit.xm ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Read-PnPTenantTemplate], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,PnP.PowerShell.Commands.Provisioning.Tenant.ReadTenantT
   emplate

Any idea?

**Comment by bcameron1231** [comment]
Hi Thanks. Did you make any changes to the starter kit? Or are you just looking to apply the starter kit to your tenant?

**Comment by alvmad** [comment]
> Hi Thanks. Did you make any changes to the starter kit? Or are you just looking to apply the starter kit to your tenant?

I did not any changes. I can deploy the starter kit but I want to make some changes for the footer, images, etc and wanted to do before deployment. Any idea?

**Comment by bcameron1231** [comment]
Hmm alright, thank you. I'm having trouble reproducing the issue.  When you say you made changes, you mean to the webparts themselves?
