### ISSUE TITLE
ErrorAccessDenied", message: "Access is denied. Check credentials and try again.

### ISSUE THREAD

**Issue by Dklein21** [pnp/sp-starter-kit#520]
## Category

- [x] Bug

## Describe the bug
Good day everyone, 
i have a problem with the personal calendar webpart in sharepoint online, i can't get the web part to load the upcoming meetings.
The only thing i saw is that there was a error message with the following text: 

error: {code: "ErrorAccessDenied", message: "Access is denied. Check credentials and try again."}

I've been trying to fix this error but could't find any solution.
Is there something i'm missing?

#### Expected or Desired Behavior

Upcoming meetings will show up.

#### Observed Behavior

Error message occures in the console 

#### Steps to Reproduce

Insert the webpart in the sharepoint website.

## Environment Details (*Development & Target environment*)
-Starter kit version 2
-OS: Windows 10
-Target Environment: SharePoint Online
-Framework: v8
-PnPPowerShell Version: newest (15.12.2021)
-Browser: Chrome v96

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Hi. Can you confirm that you the Graph Permissions have been accepted in the Admin Center?

**Comment by Dklein21** [comment]
Hey, yes im pretty sure i gave admin premissions, but in case i haven't can u tell me how it's done or how to look it up?

**Comment by bcameron1231** [comment]
If you installed the web parts via the Starter Kit Powershell, it *should* have been done already. However, if you go to the Admin Center for your tenant. On the left hand side, you'll see a menu item called **Advanced**.

Select **Advanced** -> **API Access**

On the next screen, you'll see Pending/Approved Requests. Check and see if there is a Pending requests for Graph Calendars.ReadWrite

**Comment by Dklein21** [comment]
Yes i've installed it via the starter kit, however there were still a few pending. Nothing has changed so far tho.

**Comment by bcameron1231** [comment]
hmm strange. Sounds as if you aren't authenticated or the token isn't being issued when it's requested by Graph. Do you see any other errors in the console?

**Comment by Dklein21** [comment]
Hey,
the problem is fixed now, i think it needed some time for the syncronisation.
Thank you so much for your help, i wouldn't have found it without you!!
