### ISSUE TITLE
Unable to use Starter Kit V2 template

### ISSUE THREAD

**Issue by zulujames** [pnp/sp-starter-kit#522]
## Category

- [x] Bug

#### Expected or Desired Behavior

Unable to install the PnP file using powershell following the instructions provided. Powershell provides an error preventing install (see below). I am having to authorise into the Tenant using Interactive MFA. Please can you advise what I am doing wrong. Thanks

PS D:\sp-starter-kit\provisioning> Invoke-PnpTenantTemplate -Path .\starterkit.pnp
Invoke-PnpTenantTemplate : '>' is an unexpected token. The expected token is '='. Line 15, position 76.
At line:1 char:1
+ Invoke-PnpTenantTemplate -Path .\starterkit.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Invoke-PnPTenantTemplate], XmlException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Tenant.InvokeTenantTemplate

## Environment Details (*Development & Target environment*)

- **Starter kit version**: [v2 for current version]
- **OS**: [Windows 10]
- **Target Environment**:[SharePoint Online]
- **Framework**: [Node.js v6/v8/v10/v12]
- **PnPPowerShell Version** : [5.1.22000.282]
- **Browser(s)**: [e.g. Chrome v97]

**Comment by eoverfield** [comment]
Unfortunately MFA is not supported at this time:
https://github.com/pnp/sp-starter-kit/blob/master/documentation/common-provision-results.md#error-invoke-pnptenanttemplate--the-remote-server-returned-an-error-401-unauthorized

**Comment by zulujames** [comment]
Good afternoon,
This issue has not been resolved. I am receiving the same error despite turning off all MFA authentication.

Invoke-PnPTenantTemplate: '>' is an unexpected token. The expected token is '='. Line 15, position 76.

Thanks

James
