### ISSUE TITLE
Team Site Footer Link Conflict

### ISSUE THREAD

**Issue by robertcaretta** [pnp/sp-starter-kit#55]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Links should not overlap. I would suggest moving the "Edit MyLinks" to inside of "My Links" which is left-aligned.

#### Observed Behavior
Footer links overlap.

#### Steps to Reproduce
Just a visual review. See attached.
![pnp_departmentfooter](https://user-images.githubusercontent.com/1613085/41861804-e1020fe8-7867-11e8-822f-f8a653ab7306.PNG)

**Comment by PaoloPia** [comment]
Hi @robertcaretta,
Thanks for your feedback. We're working on it, but I cannot share/guarantee any delivery date for that fix. Please, stay tuned.
