### ISSUE TITLE
Is the Stock Information Web Part really deprecated?

### ISSUE THREAD

**Issue by igord93** [pnp/sp-starter-kit#565]
-Question

Is the Stock Information Web Part really deprecated?
I really liked this feature and I would like to add it my tenant, but saw that in the documentation here it is saying deprecated.

We are heading towards the new SharePoint online leaving behind our old 2013 server.

Actually looking at this SharePoint Starting Kit V2 (with e-mail and calendar on the home screen) I will probably choose that over the The Landing page on the Look Book we just provisioned, so I won't put my time there if this is working.

But I will only do so if the stock information web part works.

Thanks in advance.

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Hi, yes indeed it is deprecated. It may still work though. :)
