### ISSUE TITLE
Cant upload starterkit.pnp

### ISSUE THREAD

**Issue by Martin-av** [pnp/sp-starter-kit#567]
Hi all,

Iam trying upload starterkit.pnp to our SHP online but i still have issues and i dont know what Iam doing wrong. Please can somebody help me? Iam sending screen below with error. I do everythink like in manual from GitHub here step by step.

![image](https://user-images.githubusercontent.com/101725526/158609306-4bf8565d-5c78-4014-ae88-38332b82bbc0.png)

Thanks a lot !:)
Martin

**Comment by bcameron1231** [comment]
Hi, thank you for the response. It looks like you are using a previous version of PnP PowerShell? We no longer support the older version of PnP Powershell. Can you try the latest version and use the invoke-pnptenanttemplate command?

**Comment by Martin-av** [comment]
Hi thank you for your answer i will try it and give you response.
