### ISSUE TITLE
Filter WebPart "People Directory"

### ISSUE THREAD

**Issue by nehank08** [pnp/sp-starter-kit#568]
I wouls like to filter all the service accounts from the webpart. How can I do that?

**Comment by gretchunkim** [comment]
@nehank08 I'll think the easiest way to start will be to create a separate group in azure active directory without all serivce accounts. 

Then in the SharePoint only inclue or grant access to user without the service account.  Do you have a separate user groups that are non-service accounts?

**Comment by gretchunkim** [comment]
I found even a better thread that answers your questions: 

https://github.com/pnp/sp-starter-kit/issues/562
