### ISSUE TITLE
Read-PnPTenantTemplate

### ISSUE THREAD

**Issue by jcajun** [pnp/sp-starter-kit#574]
I am new into this pnp coding and sharepoint starterkit. I an learning how to develop and was trying to edit the starter.xml and run the read-pnptenanttemplate cmdl and I get the following error messages:

Read-PnPTenantTemplate: The 'key' attribute is not declared.
Read-PnPTenantTemplate: The required attribute 'Key' is missing.

I cant figure out where to look to solve this problem. What I did on the xml file was change the company name where it say contoso electronics to my company and added lines to add more sites on top of Marketing and HR

**Comment by eoverfield** [comment]
Hi, would you confirm what version of PnP PowerShell you are using?
