### ISSUE TITLE
Current user has insufficient permissions to perform this operation

### ISSUE THREAD

**Issue by Shmata** [pnp/sp-starter-kit#583]
## Category

- [x] Question

## Question

I tried to install SharePoint starter kit v2. It was **NOT** possible to use the tenant admin user (admin[@]mytenant.com) because I've already activated MFA. I tried to use another user which already had administrator privileges. 
Although some webparts have been installed , during the installation process I encountered below error 

> Invoke-PnPTenantTemplate : The current user has insufficient permissions to perform this operation.  

Please tell me , **what kind of permissions do I need to perform this command** ? 

![install-starter-kit](https://user-images.githubusercontent.com/2398297/184526211-a3d2f49c-71df-4dca-b4c6-9037ca8b1c18.png)

**Comment by eoverfield** [comment]
Did you add this second use as a site collection admin directly to the app catalog site collection?

**Comment by Shmata** [comment]
@eoverfield thanks for your response, Yes I've already added second user to a site collection administrators group. 
The authenticated user which I perform that commands , has a site collection admin permission.

**Comment by llmedina** [comment]
I am having the same issue. I have even gone as far as granting the provisioning user, administrator rights to all office products, i.e., Exchange, Global, SharePoint. etc.

**Comment by eoverfield** [comment]
It is possible this is being thrown when the term set is being provisioned. 
https://github.com/pnp/sp-starter-kit/blob/v3/documentation/common-provision-results.md#error-term-set-permissions-required
