### ISSUE TITLE
ClientSideAssets not found - 0.pnp-sp_d384e6e2631b7de0a526.js

### ISSUE THREAD

**Issue by bart1792** [pnp/sp-starter-kit#584]
## Category

- [x] Bug

## Describe the bug
When adding the portal footer to a new hubsite via applying the site template it does not appear and a 404 is present in the console where 0.pnp-sp_d384e6e2631b7de0a526.js cannot be found.  Sites with the template already in place do not error.
#### Expected or Desired Behavior
Portal Footer should load
#### Observed Behavior
No footer loads and errors display in console

#### Steps to Reproduce
1. Create site
2. Assign as hubsite
3. Apply template
4. Reload site after template has applied

## Environment Details (*Development & Target environment*)
SharePoint Online

- **Starter kit version**: v2
- **OS**: [Various: Windows 10, Android]
- **Target Environment**:[ SharePoint Online]
- **Framework**: [no local compilation deployed per v2 starter kit]
- **PnPPowerShell Version** : [NA]
- **Browser(s)**: [Edge 104.0.XX]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Can you please share your site template json with us?
