### ISSUE TITLE
Starter kit error while installing npm install

### ISSUE THREAD

**Issue by JayT18** [pnp/sp-starter-kit#594]
This are my errors while using npm install in ./source/library-starter-kit-shared
which version of SharePoint framework should in use. currently i am using 1.15.2, which version should i use?
What should i do i facing this errors while installing.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by bcameron1231** [comment]
What version of node are you using?
