### ISSUE TITLE
Personal Calendar - API access

### ISSUE THREAD

**Issue by mboesjes** [pnp/sp-starter-kit#662]
Hello,

I've installed the Personal Calendar webpart to my SharePoint online tenant.
When I place the webpart on a site, it keeps trying to retrieve the calendar items en nothing happens. No items show up, and there is no error.

I've tried to reinstall the webpart, but it doesn't help.

Can anyone tell me which API access is needed by this webpart? Then I can reconfigure that and hopefully fix the problem.
Any other suggestions are also very welcome! :-)

Thanks!

**Comment by eoverfield** [comment]
The personal calendar requires the following permissions:
    "webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "MailboxSettings.Read"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Calendars.Read"
      }
    ]

Please note we are working to upgrade all webparts to spfx v1.16.1, though at this time, we have not yet gotten to the personal calendar webpart. Possibly this upgrade will help with this particular issue once it is ready.

**Comment by mboesjes** [comment]
Thanks for the quick reply!
The API permissions are correct on my tenant as I can see.
So the problem is that the calendar webpart is not yet compatible with the latest spfx at this moment?

**Comment by eoverfield** [comment]
Personal Calendar and its dependencies have been updated in the v3 branch. Refer to the comment here: https://github.com/pnp/sp-starter-kit/issues/577#issuecomment-1425024470.

The calendar webpart with the shared library and graph toolkit react solutions in the current main (v2) branch should still be working, though the v3 was just validated and worked well in our validation tenants.
