### ISSUE TITLE
Can we deploy sp-starter-kit to just a single site collection.

### ISSUE THREAD

**Issue by karthikramasubramanian** [pnp/sp-starter-kit#674]
The instructions I found in the site are for deploying this to the entire tenant.  Can we just deploy the solution (template and webparts) to just a single site collection.  The webparts should only be available in the site collection app catalog.  Can you please let me know how this can be done?

**Comment by eoverfield** [comment]
Much of this project can be deployed to an existing site collection, though you could also use the provisioning template xml to create a custom solution as well.

Breaking this down.

The webparts and other sppkgs can mostly be added individually to a site collection app catalog. You will find a sppkg for each SP component with the ./source folder. 

The problem with automation is I do not believe we can create a new site collection, then activate that site collection's app catalog, and finally install the sppkg's directly to that site collection app catalog. 

You should be able to update the provision template found in ./source/templates to only add pages to an existing site collection.

Overall aspects of what you are looking for is possible based on the included assets within this project, though we do not have an existing template to provision this project only to a scoped site collection.
