### ISSUE TITLE
Unknown Error for Invoke-PnPTenantTemplate, Invoke-PnPSiteTemplate

### ISSUE THREAD

**Issue by rajukprajapati** [pnp/sp-starter-kit#691]
When I run Invoke-PnPTenantTemplate or Invoke-PnPSiteTempalte all the sppkg solutions are successfully deploying into the app catalog. but immediately after that I get following error in PowerShell Console:
Invoke-PnPTenantTemplate: Unknown Error

While check in the PnPTraceLog, I found below error:

pwsh Error: 0 : 2024-06-06 11:29:58.1303	[PnP.Framework]	[0]	[Error]	ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: Unknown Error
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServerAsync(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
ServerErrorCode: -1
ServerErrorTypeName: Microsoft.SharePoint.Client.UnknownError
ServerErrorTraceCorrelationId: f1e42fa1-60c3-5000-9e1f-0bac8e69163f
ServerErrorValue: 
ServerErrorDetails: 
.	0ms	
pwsh Information: 0 : 2024-06-06 11:29:58.1306	[Tenant Settings]	[19]	[Debug]	Code execution scope ended	399964ms	8a459c9d-1610-44ed-8591-b903a8e676c2
pwsh Information: 0 : 2024-06-06 11:29:58.1308	[ProvisioningTemplate WebHook Call]	[19]	[Debug]	Code execution scope started	0ms	8a459c9d-1610-44ed-8591-b903a8e676c2
pwsh Information: 0 : 2024-06-06 11:29:58.1308	[ProvisioningTemplate WebHook Call]	[19]	[Debug]	Code execution scope ended	0ms	8a459c9d-1610-44ed-8591-b903a8e676c2
pwsh Information: 0 : 2024-06-06 11:29:58.1309	[Provisioning]	[19]	[Debug]	Code execution scope ended	401338ms	8a459c9d-1610-44ed-8591-b903a8e676c2

Please help!

**Comment by eoverfield** [comment]
What version of powershell and PnP powershell are you using?

**Comment by rajukprajapati** [comment]
**PowerShell** - 7.4.2
$psVersionTable.PSVersion
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      4      2

**PnP PowerShell** - 2.4.0
Get-Module PnP.PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   2.4.0                 PnP.PowerShell                      {Add-PnPAlert, Add-PnPApp, Add-PnPApplicationCust…

**Comment by rajukprajapati** [comment]
Not sure, what was the actual issue. But I am able to get over it by breaking down starterkit in following sequence:
1. As all the sppkg solutions were successfully deployed. I removed them from starterkit.xml saved it as a new pnp template and used for provisioning (this did not fix the issue). 
2. Next, I removed below section from starterkit.xml 
    <<pnp:WebApiPermissions>>
          <pnp:WebApiPermission Resource="Microsoft Graph" Scope="Sites.Read.All"/>
          <pnp:WebApiPermission Resource="Microsoft Graph" Scope="Contacts.Read"/>
          <pnp:WebApiPermission Resource="Microsoft Graph" Scope="User.Read.All"/>
          <pnp:WebApiPermission Resource="Microsoft Graph" Scope="Mail.Read"/>
          <pnp:WebApiPermission Resource="Microsoft Graph" Scope="Calendars.ReadWrite"/>
          <pnp:WebApiPermission Resource="Microsoft Graph" Scope="Group.ReadWrite.All"/>
          <pnp:WebApiPermission Resource="Microsoft Graph" Scope="MailboxSettings.Read"/>
          <pnp:WebApiPermission Resource="Microsoft Graph" Scope="Tasks.ReadWrite"/>
          <pnp:WebApiPermission Resource="Microsoft Graph" Scope="People.Read"/>
        </pnp:WebApiPermissions>
saved it as a new pnp template and used it for provisioning and it works.

Please let me know if I was missing something or some additional steps/pre-requisites require for the above starterkit activities accomplishment. As per my understanding while approving these API Access thru PnP script it was failing.
