### ISSUE TITLE
PnP Search Web Part in SharePoint Online Not Filtering Results Dynamically Based on URL or Metadata

### ISSUE THREAD

**Issue by Darwin698** [pnp/sp-starter-kit#692]
**Category**
 Question
**Question**
Hello!

I am creating a video catalog in SharePoint Online, and I need a single page that dynamically reads metadata from the navigation and filters results in the Search Result web part based on the selected term.

According to the resource https://microsoft-search.github.io/pnp-modern-search/usage/search-results/tokens/#where-can-i-use-tokens, it suggests using the command: {|owstaxidmetadataalltagsinfo:{Page.myTaxonomyMultiColumn.TermID}}. However, unfortunately, this command is not working—search results return 0. I have also tried owstaxidmetadataalltagsinfo:"{URLToken.1}" to filter by a word from the URL, but the result is still 0.

I’ve tried commands like {Page.Term}, {Page.TermID}, owstaxidmetadataalltagsinfo:"*{Term.Name}*", and many others, but they all return 0 results.

However, when I specify the term name or GUID directly in the query (e.g., owstaxidmetadataalltagsinfo:"software"), the results are displayed correctly.

Could you please clarify whether this is the expected behavior? Does the PnP Search Result Web Part not support dynamic data retrieval from the URL, or am I using incorrect syntax?

Thank you in advance for your help!

**Comment by eoverfield** [comment]
I suggest posting this query over on the pnp modern search repo:

https://github.com/microsoft-search/pnp-modern-search/issues.
