### ISSUE TITLE
Is SP Starter Kit v3 "supported" on a renamed tenant?

### ISSUE THREAD

**Issue by cloudydam** [pnp/sp-starter-kit#693]
Hiya,

I have a SP Starter Kit v3 default installation running on a test tenant. Forgive me for being vague, but I remember it as running fine and all web parts on the portal front page / communication site displayed fine. However, after having performed a tenant rename the Latest Email web part started failing with message "Token renewal operation failed due to timeout".

It might not be related but the question is: is SP Starter Kit v3 "supported" on renamed tenants? 

Sincerely,
Chris

**Comment by eoverfield** [comment]
There are no known issues with renaming a tenant.
The error itself looks to be a graph api error. The email web part uses graph to retrieve a user's email. in particular a call to:
me/mailFolders/Inbox/messages

The graph call is made by using the msGraphClientFactory:
`
this.context.msGraphClientFactory
        .getClient('3')
        .then((client: MSGraphClientV3): void => {
          this.graphClient = client;
          resolve();
        }, err => reject(err));
        ...
`
possibly the renaming broken the permission within your tenant to set up this client?

Have you tried removing and re-adding the webpart?

**Comment by cloudydam** [comment]
Thanks, Eric.

I tried removing/re-adding again - no change.
 
It is not a tenant I use that often, so it is probably related to something else, then. The API access page is also failing with this message "Error ensuring domain-wide principals: monitor_window_timeout: Token acquisition in iframe failed due to timeout.". I guess I'll start by sorting that out and hope it also fixes the web part.

I'll close the question again :-)
